### ISSUE TITLE
Hmr no apply changes when I alter Datatable columns.

### ISSUE THREAD

**Issue by galiazzi** [primefaces/primevue#1106]
When I change the data table columns with `npm run serve`.
The changes do not render the datatable again.

This occurs in other components that have some logic in their slots, such as accordion and tabs

Do you have any plans to make hmr work on these components?

**Comment by Anubarak** [comment]
I have the same issue. I always just receive the following notification in my network tab
```JSON
{"type":"invalid"}
```
![image](https://user-images.githubusercontent.com/6122122/112851588-6ac47780-90ab-11eb-8aa1-726069139b2a.png)

**Comment by cagataycivici** [comment]
I'm not sure if there is anything we can do on our side, could be Vue Core related, feel free to create a PR if there is a solution.

**Comment by Anubarak** [comment]
@cagataycivici This is PrimeVue related, because of the way you use your components. A pull request would require to re-write a massive amount of your components.
I'm not sure why you always close all those issues right away without even trying to understand the underlaying problems.
If you don't want to fix it, feel free to tell us. I'll stop to create new issues in that case

**Comment by ERROPiX** [comment]
@cagataycivici this issue is pretty obvious, you have used duplicate key values for all the row columns and slots

![image](https://user-images.githubusercontent.com/6576868/148132031-713a049d-5693-47af-990f-7c30636c1790.png)

This should be fixed easily by creating the key based on field-index value, e.g. `id-0`, `name-0`

Same solution for the columns slot, the key be generated with this template field-index-slot, e.g. `name-0-header`, `name-0-body`

**Comment by ERROPiX** [comment]
@yigitfindikli can you provide a fix for this issue?
