### ISSUE TITLE
HeaderCell > DTHeaderCheckbox > filterDisplay !== 'row'

### ISSUE THREAD

**Issue by welcome14** [primefaces/primevue#1258]
Hi,
why is disabled the checkbox-all header if i set filterdisplay == row ?

How can i active checkbox in header?

**Comment by cagataycivici** [comment]
It is rendered at the header;

https://primefaces.org/primevue/showcase/#/datatable

Unable to replicate with the latest PrimeVue 3.4.1. If the issue persists, please try with the latest version available and create a new ticket with our codesandbox template fork so that we can work on it again. Thank you.

**Comment by welcome14** [comment]
I solved it with filterDisplay = "menu" instead of filterDisplay = "row"
