### ISSUE TITLE
docs: SFC file import is not correct

### ISSUE THREAD

**Issue by develar** [primefaces/primevue#1364]
incorrect docs page: https://primefaces.org/primevue/showcase/#/setup

In the docs stated that:

> SFC files are available in the npm distribution and if you'd like to use SFCs directly, add /sfc as a suffix when referencing an import path

but actually no separate `sfc` directory, `.vue` files located in the rood dir of component.
<img width="267" alt="Screenshot 2021-07-04 at 11 07 51" src="https://user-images.githubusercontent.com/350686/124379565-1a674200-dcb8-11eb-9280-960f263188a5.png">

**Comment by craigrileyuk** [comment]
Look in the package.json file

```
{
  "main": "./datatable.cjs.js",
  "module": "./datatable.esm.js",
  "unpkg": "./datatable.min.js",
  "types": "./DataTable.d.ts",
  "browser": {
    "./sfc": "./DataTable.vue"
  }
}
```
The link between the /sfc path and the component is listed there as a way to standarise the import process.

**Comment by develar** [comment]
Hmm... indeed. You are right, thanks. 

Still, the code in docs is not correct, if I am not wrong:

Vite error for import path `"primevue/tabmenu/sfc"`: 

> [vite] Internal server error: Failed to resolve import "primevue/tabmenu/sfc" from "src/App.vue". Does the file exist?

Phrase "add /sfc as a suffix when referencing an import path" is not correct, suffix `/sfc` is wrong.
Import path `import TabMenu from "primevue/tabmenu" works for me.

**Comment by craigrileyuk** [comment]
Which version of PrimeVue are you attempting to import from? Because the Vue2 version doesn't have sfc imports.

**Comment by develar** [comment]
`3.5.1`. Vue 3. 

Actually, if you use Vite, you don't need to import components manually, you can simply use [vite-plugin-components](https://github.com/antfu/vite-plugin-components) 
Currently, prime vue support [is not bundled](https://github.com/antfu/vite-plugin-components/tree/main/src/resolvers) but there is a pull request — https://github.com/antfu/vite-plugin-components/pull/66 

My goal is not to "how to make things work", but to evaluate prime vue applicability (currently I use element plus ui framework).

**Comment by tugcekucukoglu** [comment]
`SFC files are available in the npm distribution and if you'd like to use SFCs directly, add /sfc as a suffix when referencing an import path. This will instruct your bundler to process the *.vue files in your local build instead of using the compiled output. One use case for this approach is optimizing for SSR by removing whitespaces.`

The documentation seems to me correct. There is no any info that there will be a sfc directory. 

[https://vuejs.org/v2/cookbook/packaging-sfc-for-npm.html#How-does-npm-know-which-version-to-serve-to-a-browser-build-process](https://vuejs.org/v2/cookbook/packaging-sfc-for-npm.html#How-does-npm-know-which-version-to-serve-to-a-browser-build-process)
