### ISSUE TITLE
Allow to automatically remove focus on AutoComplete after a suggestion is selected

### ISSUE THREAD

**Issue by mswawola-aerinsight** [primefaces/primevue#1781]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```
**Current behavior**
The AutoComplete component remains focused after selecting a suggestion in the list.

**Expected behavior**
Because the focus is realized by adding the `p-inputwrapper-focus` CSS class on the `span` tag, none of the javascript methods to blur it manually works (because it's a CSS class and not a "real" focus). I understand that use cases where keeping the component focused may exist, but it could also be a great addition to allow the automatic blur of the component once a selection is made.

**Comment by tugcekucukoglu** [comment]
After a suggestion is selected, cursor is still stays in the autocomplete input. So this is the expected behavior.

**Comment by okmkey45** [comment]
Hello. I would like to bring this up again.

@mswawola-aerinsight did you find a way to achieve this?

@tugcekucukoglu I agree that the way it is an expected behavior but, I also think that allowing automatic blur on the main input after a suggestion is selected makes sense as well. Like for example, right now, I'm working on a custom filter component where users can modify values from chips. Take a look at the next screenshot please. Here's the flow:

1. User clicks the main input
2. Dropdown with options are displayed
3. User clicks a suggestion
4. Dropdown is hidden
5. A chip is added to the main input with `<filter_name> contains <criteria>`. Keep in mind that `criteria` is empty at this point
6. At this point, I'd like to focus automatically that little criteria input in order for the user to enter text

![image](https://github.com/primefaces/primevue/assets/22939440/4286db7d-26cf-4291-b92a-5614004dd3dd)

Note: as an example, the criteria input is the one that contains the purple text.

So, I cannot focus the criteria input inside the chip automatically because after closing the dropdown and the chip is added to the main input, the input remains focused. Without this blur feature after selection, user would have to click the chip again in order to add the criteria

But to be fair, maybe I'm using the wrong component. If I am, can you point me into the right direction?

Thanks for any help

**Comment by yorickp** [comment]
Valid use case indeed 👍

It can be achieved by listening to the AutoComplete its `onFocus` event, and, inside your listener, calling `.blur()` on the AutoComplete its input element reference.

Not a Vue developer, but in Angular this would be something like (and I assume this can be translated to PrimeVue fairly similar):

```
onFocusAutoComplete(): void {
    if (whenFocusedRightAfterSuggestionSelection) {
        this.autoCompleteViewChild.inputEL.nativeElement.blur();
    }
}
```

To get it to behave as expected for all interaction use cases, you won't want the input its blur event to be triggered on every trigger of the AutoComplete its onFocus listener, but only when that focus kicks in right after a suggestion got selected. So the full implementation will also require you to listen to the AutoComplete its `onBlur` and `onSelect` events, to keep track of the interaction state the user was in the moment the AutoComplete its `onFocus` event got emitted.

**Conclusion**: Although it would be helpful for many of us to have that behaviour more explicitly available on the AutoComplete component, the requested behaviour ís achievable without any need for internal changes to that AutoComplete component.
