### ISSUE TITLE
3.9.0 undocument breaking change Progressbar DOM order changed

### ISSUE THREAD

**Issue by maidzen** [primefaces/primevue#1783]
With 3.9.0 progressbar got updated 

https://github.com/primefaces/primevue/issues/1752

This change moved progress-label inside progress-value which changes the DOM
Custom CSS is now broken.

The Label position should be a propertie option

**Comment by Rakasch** [comment]
Position of the text changed, due to the different dom.
Before update, text was centered in main bar.
![image](https://user-images.githubusercontent.com/8471027/142614015-5009bf74-7dcf-4965-b9d7-2080447c9c87.png)

After update, text is centered in value bar.
Text is not visible, when value is close to zero.
Text is misplaced, if value is bigger 100%.
![image](https://user-images.githubusercontent.com/8471027/142614183-927aa664-e27e-44c7-a215-50465e333187.png)

**Comment by rweisse** [comment]
This is the reason why I can not migrate to PrimeNG 13. The progressbar is some kind of unusable now.

1. I have to overwrite the colors of `.p-progressbar-label`by myself back to normal. The #1752 said that the old colors were not perfect for every background. But now they have been made even worse (see: https://github.com/primefaces/primevue/commit/fb7b2b24cc6747a8d6e74989299626a7e5c2ef71)
2. As @maidzen said the `div` of class `.p-progressbar-label` moved inside of the div of class `p-progressbar-value` (see: https://github.com/primefaces/primevue/commit/fb7b2b24cc6747a8d6e74989299626a7e5c2ef71#diff-e40752689771020ea1d5b3b63d5314a649830fe7adf3f91df20e031c909b729f). This results in a (partially) invisible progress label with small and big progresses because the label is listed inside of the progress bar now. And even when it is visibile it looks really weird now.
4. As @maidzen said this is a breaking and undocumented change.

The "new" design of a progress bar is not usable and unfamiliar. IMHO the complete changes of https://github.com/primefaces/primevue/issues/1752 should be reverted.

**Comment by NeluQi** [comment]
If you use normal text percentages from 0 to 100, the problem does not occur.

I think we need to find some kind of compromise, or make a setting in the component (disable or enable centering). I still think if the text is centered, then it reads poorly


Or fix the problem with "a (partially) invisible progress label with small progresses"

For example, you can center the maximum progress (or when it is more than 50%), and with minimum progress, if there is not enough space for the text, display it with a tooltip.

Ideally, I think to make a setting in the component, which will center or not

**Comment by Rakasch** [comment]
@NeluQi If you think about statistics, 300% can be a very normal value.

**Comment by rweisse** [comment]
Hi @NeluQi,

this is how my ProgressBars looking right now :)
![grafik](https://user-images.githubusercontent.com/7416092/145823113-f4adbda5-0e18-4d93-b760-78fc302943a3.png)

As you can see small values are a big issue. Placing the label inside the bar is much more complicated than just placing it in the center of the whole component because handling potentially inappropriate colors with some css is much easier than handling dynamic width of a component and reacting on its current progress and displaying tooltips.

Please don't get me wrong. I can understand the desire to provide other layout options here. And I would be very happy if there were more layout options. I think it's great! But that should not prevent the standard layout of progress bars that we have known for decades from being supported. And as long as this new layout cannot be displayed without errors, it should not be available. Especially not as a default layout and even not if this change is not documented.

**Comment by NeluQi** [comment]
You need to think about how best to do it. There is a problem with small values.

Now in my project it looks like this
![image](https://user-images.githubusercontent.com/16963395/145958939-e8eeb712-423f-4485-90e8-de04ea016a43.png)
![image](https://user-images.githubusercontent.com/16963395/145958967-71aba605-ba11-4745-bc68-3b2997929734.png)
![image](https://user-images.githubusercontent.com/16963395/145959091-eaad01d2-33a6-478f-80bf-4ded0a30289f.png)




I propose to think about the location of the text.
And it seems that a setting is needed about where to place the text about the progress

Maybe render the text behind the progress bar? Top or bottom, and make the progress bar smaller?

Below I will attach several options for the location of the progress text.


![image](https://user-images.githubusercontent.com/16963395/145958250-420350fa-f95a-42cd-a45c-fe80ef11f7b7.png)

![image](https://user-images.githubusercontent.com/16963395/145958306-5f2c8594-3410-4ad0-bdc4-6feea1fcea87.png)


![image](https://user-images.githubusercontent.com/16963395/145958068-fde2de3d-afca-4ad4-a2af-398f5d43edb2.png)

![image](https://user-images.githubusercontent.com/16963395/145958171-284ffd28-867f-436d-850c-1c2948d65ab7.png)

![image](https://user-images.githubusercontent.com/16963395/145958214-5d4d7239-3595-4cf8-8d17-ddca493f885c.png)

**Comment by maidzen** [comment]
as in my issue post written the text position should be an option (prop) because there are valid use cases for all of them

<ProgressBar valuePosition="center" /> (Old style)

<ProgressBar valuePosition="inside" /> (new Style)

<ProgressBar valuePosition="outside" /> (Post above)

**Comment by riskysciolism** [comment]
As stated by @rweisse the changes indeed should be reverted.
Regarding @NeluQi  suggestions, I think it is also important to note the need for rather narrow presentation in tables:
![image](https://user-images.githubusercontent.com/20141732/218672873-bbe1ea3e-12e2-4cd4-8620-234e13ec187b.png)

**Comment by JoseGoncalves** [comment]
No progress on this issue?
No known workaround?

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
