### ISSUE TITLE
DataTable event "filter" not called with lazy mode.

### ISSUE THREAD

**Issue by Sellec** [primefaces/primevue#180]
How can we determine changed filter values for lazy loading?
We have "page" event for page changes, "sort" event for sorting and ... we need to use vue data change mechanics to catch filter values change events?
In PrimeUI, you have a very nice mechanism - only one method "dataSource" which called on every paginate/sort/filter events and takes an agrument with all arguments. With filtering there are another nice thing - after changing filter value its calls "dataSource" after some moments, i.e. its waiting for some time - maybe user input is not ended.

**Comment by cagataycivici** [comment]
It is by design to give the page author more control over the filter elements since in PrimeVue, filter elements are defined at the template so you can choose what UI to use and which event to trigger the filter like change, input, blur. Downside is a bit of more work on your side as you have to call the backend call using these event.

A more enhanced example with a backend is being worked on and will be available at a github repository.
