### ISSUE TITLE
Improve TypeScript Definitions on all components 

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primevue#1836]
All definitions have been rewritten so that users can use the components more easily.

**Comment by ReevMich** [comment]
There seems to be a missing property for `ConfirmationOptions`interface. Its missing `header: string`. @mertsincan, do you want me to open an issue for this?

**Comment by mertsincan** [comment]
Hi @ReevMich,

Of course! Also, you can create a PR ;)

**Comment by awulkan** [comment]
We're having some problems with DataTable filters after this update. Everything still works, but TypeScript is throwing errors. We're trying to figure it out, but if not, we'll create an issue. 

The problem we're facing appears caused by this line: https://github.com/primefaces/primevue/commit/9a9ae8660ba2c0b04731e7ec24040a37f382e995#diff-37a8b4c9777d570bdbd9165b983cfaa3a208dd286f8ea9ae8e28e1f3a50f888bR77

TypeScript says that there is no `.value` on our `filters['global'].value` in our template code.

**Comment by cm-santos** [comment]
TabPanel header slot definition seems to be missing.

`TS7053: Element implicitly has an 'any' type because expression of type '"header"' can't be used to index type '{ default: unknown; }'.
  Property 'header' does not exist on type '{ default: unknown; }'.

58                     <template #header>`
