### ISSUE TITLE
DataTable rowSelect event triggers rowClick

### ISSUE THREAD

**Issue by fairking** [primefaces/primevue#194]
Primevue: 1.0.4
In a situation when DataTable has multi selection mode the `row-click` is triggered when rows are being selected. Tried `.prevent` but didn't help.

```
<DataTable 
    :selection.sync="selectedRows"
    :row-hover="true"
    data-key="id"
    //@row-select.prevent.stop="rowSelect" // added just to check a workaround
    @row-click="rowClick">
    <Column selection-mode="multiple" header-style="width: 32px;text-align:left;"></Column>
    ... columns
</DataTable>
```
To reproduce the issue try to select rows (tick checkboxes) and you wil see that the `row-click` is triggered.
In my app the `row-click` opens a dialog window with the row details. But selecting rows should not trigger the dialog window.
There might be the same issue in a single select mode too (think radio boxes).

**Comment by fairking** [comment]
If someone has a workaround please let me know. Thanks.

**Comment by fairking** [comment]
Please review my PR guys. Hope it will help you with the milestone.

**Comment by cagataycivici** [comment]
I'm sorry but this is expected, row-click is triggered whenever a row is clicked. Use row-select to open the dialog instead, the event has a type prop like "row", "radiobutton" and "checkbox" for further check.

```javascirpt
onRowSelect(event) {
   if (event.type === 'row') //open dialog
  else if (event.type === 'radiobutton') //something else
} 
```

So my suggestion would be removing row-click and focus on row-select. row-select is also better since it is not triggered when clickable components inside the row are clicked like form elements.

**Comment by fairking** [comment]
> Use row-select to open the dialog instead

`row-select` is not triggered when I click on rows.

My `DataTable` config is:
```
<DataTable
			ref="dt"
			:value="rows"
			:selection.sync="selectedRows"
			:paginator="true"
			:rows="pageSize"
			:lazy="true"
			:loading="loading"
			:total-records="totalRows"
			:row-hover="true"
			class="p-datatable-responsive"
			data-key="id"
			paginator-position="bottom"
			:export-filename="exportFileName"
			:auto-layout="true"
			sort-field="sortField"
			:sort-order="sortOrder"
			@page="pageData"
			@sort="sortData"
			@row-select="onRowSelect" // not triggered
		>
			<Column selection-mode="multiple" header-style="width: 32px;text-align:left;"></Column>
```

**Comment by fairking** [comment]
Found a solution, very ugly but it works:
```
rowClick(e) {
    if (!e.originalEvent.target.classList.contains('p-checkbox-box') 
&& !e.originalEvent.target.parentElement.classList.contains('p-checkbox-box'))
        this.$emit("row-click", e.data); // Open dialog with row details.
			},
```

**Comment by fairking** [comment]
@cagataycivici I think the issue needs to be reopened.

**Comment by daprezjer** [comment]
> Found a solution, very ugly but it works:
> 
> ```
> rowClick(e) {
>     if (!e.originalEvent.target.classList.contains('p-checkbox-box') 
> && !e.originalEvent.target.parentElement.classList.contains('p-checkbox-box'))
>         this.$emit("row-click", e.data); // Open dialog with row details.
> 			},
> ```
> 
> p.s. the parent check required when checkbox is unticked.

@fairking this is basically what I ended up having to do. Has anything changed in the meantime to make this work better?

@cagataycivici while I agree this is "expected", I'd argue it is only because more sophisticated logic isn't available. This essentially means that two of your most powerful features on DataTables - row-click and selections - can't work together.

A sample use case here is that you want to be able to select rows for another action (like the pop actions below), but click into the row for any other column clicked.

![Image](https://github.com/user-attachments/assets/b63f822d-f7e3-4561-806c-2a7a54642b65)

Oddly, when the checkbox is checked, it _doesn't_ trigger the row-click, but when it's unchecked, it does (at least in v3, not sure about v4). So it's not actually working as expected either.

Let me know if I should ask for this issue to be reopened, ask for this to be reopened - https://github.com/primefaces/primevue/issues/228 - or if it's just not going to happen. Thanks for all the hard work!
