### ISSUE TITLE
DataTable bug when using multiple selection with lazy mode

### ISSUE THREAD

**Issue by timurash** [primefaces/primevue#2051]
[x] bug report

https://codesandbox.io/s/primevue-2-datatable-checkbox-selection-in-lazy-mode-ts5dc?file=/src/App.vue

**Current behavior**
When using lazy option with multiple selection, top checkbox of multiple selection is not getting selected when all rows is selected, When hitting top checkbox, all rows gets selected, but the checkbox itself doesn't get selected

**Expected behavior**
Top checkbox gets selected when all fields is selected

**Minimal reproduction of the problem with instructions**
Open codesandbox, click top checkbox. All fields getting selected, but top checkbox is not

* **Vue version:** 2.6.14
* **PrimeVue version:** 2.8.0

**Comment by tugcekucukoglu** [comment]
In lazy mode, you need to control/check all the rows checked or not. Because lazy load did not load entire data and even if you checked all rows in the page it still acts like that there are more data that is not checked. To manage this please check this example [https://codesandbox.io/s/serene-khorana-2whl1?file=/src/DataTableLazyDemo.vue](https://codesandbox.io/s/serene-khorana-2whl1?file=/src/DataTableLazyDemo.vue). It's PrimeVue3 example but logic is the same.

Thanks,

**Comment by timurash** [comment]
@tugcekucukoglu DataTable component in PrimeVue 2.8.0 doesn't have selectAll prop and not emitting select-all-change event like DataTable component in PrimeVue 3

How can i achieve the behaviour i need in PrimeVue 2?

Can you provide some example on PrimeVue 2?
