### ISSUE TITLE
Active filter css class in datatable is not applied on the button

### ISSUE THREAD

**Issue by DisegnAle** [primefaces/primevue#2355]
I can see from the demo 'p-column-filter-menu-button-active' css class is is applied  to the filter button (p-column-filter-menu-button) when a filter in the datatable is applied. in my case this is not happening. 

Does anyone know the possible reasons?

**Comment by tugcekucukoglu** [comment]
What is your case? Without codesandbox we could not replicate it. Please reopen this same issue with an example?

**Comment by nickyadvokaat** [comment]
I ran into the same issue, because I was using custom filter constraints. 
In my case I needed to use an [Operator](https://primevue.org/datatable/#api.datatable.interfaces.DataTableOperatorFilterMetaData) even when I don't use it in my filter.
So anyone running into this use, check if your custom filters are causing this
