### ISSUE TITLE
Add JumpToPageDropdown to paginator template

### ISSUE THREAD

**Issue by wanglin86769** [primefaces/primevue#247]
I think it is useful when there is a large amount of data in the table and PrimeFaces for JSF has this feature.
https://primefaces.github.io/primefaces/8_0/#/components/datatable

**Comment by cagataycivici** [comment]
I agree, coming in 2.0.0.

**Comment by nclemeur** [comment]
I think this would be really useful and even required when working with many pages. Try getting to page 120 currently and it is a really painful process.

Maybe it is a matter of adding a few slots so that the component could be more easily customized. For example I would like to replace the current PageLinks implementation with a dropdown/type in box...

**Comment by cagataycivici** [comment]
We'll add it to near future roadmap, other Prime libraries have it.

**Comment by cagataycivici** [comment]
Ready!
