### ISSUE TITLE
Menu not rendering sub menu

### ISSUE THREAD

**Issue by tony-nz** [primefaces/primevue#2502]
While using the 'primevue/menu' component, sub menus (item -> items[]) cannot be rendered, is there anyway to go about this?

**Comment by tugcekucukoglu** [comment]
Please check this [example](https://codesandbox.io/s/p1dx3w). How can we replicate this issue?

**Comment by tony-nz** [comment]
Hey there, 

Please see https://codesandbox.io/s/priceless-firefly-jhczin?file=/src/MenuDemo.vue

I've modified the items model to reflect what I am having trouble with.

Click the toggle button and you'll see the ContextMenu component: 'Navigate > Vue Website > Sub menu' vs the inline Menu component which is missing the submenu under 'Vue Website'.

Or would I be best to use the context menu and fix its location?

**Comment by tugcekucukoglu** [comment]
TieredMenu can be used for nested menus.

**Comment by agm1984** [comment]
The TieredMenu works, except the menu goes off the side of the screen:
![image](https://user-images.githubusercontent.com/17655219/177641141-1e458238-b137-4f05-8078-ddcd5e4b68f2.png)

I've been using the ContextMenu because it opens the submenu items to the left of the menu item when it opens near the right side of the screen, but our designer just complained yesterday that the menu opens relative to the mouse coordinates, not the button.

TieredMenu also fails to work properly when the menu items is a computed prop. It only works when the menuItems array is a ref or reactive, So you can't disable/enable menu items based on current state.
