### ISSUE TITLE
Tooltip new fitContent property

### ISSUE THREAD

**Issue by ataylor32** [primefaces/primevue#2536]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**

https://codesandbox.io/s/brave-leaf-f6zl7l?file=/src/App.vue

**Current behavior**

Sometimes the tooltip's automatic positioning works great and other times it doesn't. Here is a short video that demonstrates this:

https://user-images.githubusercontent.com/1054222/167943392-7c419e0f-5709-4fbe-868a-99f1c18b58c4.mp4

**Expected behavior**

If the tooltip detects that it doesn't have much room for words to be displayed in a manner that's easy to read, it should choose a different position.

**Minimal reproduction of the problem with instructions**

Go to the CodeSandbox link above and hover over the buttons. See the above video for a demo of the bug.

**What is the motivation / use case for changing the behavior?**

Fixing this would make tooltips easier to read.

**Please tell us about your environment:**

I develop on macOS using Visual Studio Code

* **Vue version:** 3.X

* **PrimeVue version:** 3.12.X

* **Browser:** I've confirmed this issue using Chrome on both macOS and Windows

**Comment by tugcekucukoglu** [comment]
It's an edge case. As you can see tooltip works fine for Card 2 and Card 3 in your example. As expected Card 1 has padding and/or margin so tooltip directive thinks that can be positioned itself but it has word-break css rule. Because of [this issue](https://github.com/primefaces/primevue/issues/1512). Anyway still has a solution with a small changes. Please check this [codesandbox example](https://codesandbox.io/s/trusting-waterfall-96yyyz?file=/src/App.vue:708-781.)
