### ISSUE TITLE
Please provide a method to set paginator  programmatically

### ISSUE THREAD

**Issue by zortext** [primefaces/primevue#2705]
### Describe the feature you would like to see added

Datatable keeps current page number active when a new dataset is loaded. A method or parameter would be nice to set the page to a desired number programmatically. 

### Describe the solution you'd like

` <DataTable :value="customers" :paginator="true" :rows="10" :pageNumber="page">`
 
```
const page=ref(1);
//set dynamic page number 
page.value=2;
return {page,customers}  
```

**Comment by a20246** [comment]
**:first="form.page === 1 ? 0 : (form.page - 1) * form.size"**

In my approach, I've set up the :first attribute to manage where the component's first page begins. If form.page is 1, the component starts at index 0, indicating its initial page. However, since my pagination begins at 1, for other pages (when form.page isn't 1), I calculate the starting point using (form.page - 1) * form.size. This ensures that the pagination starts at 1 for the subsequent pages.
