### ISSUE TITLE
Add getVirtualScrollerRef method to DataTable to access virtualScroller's reference

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primevue#2756]
Users can use all public method of VirtualScroller API. For example; scrollToIndex

**Comment by msladek** [comment]
@mertsincan this issue seems incomplete since the functionality `getVirtualScrollerRef` is neither documented in the [DataTable API](https://primevue.org/datatable/#api.datatable.props) nor is it typed in [primevue/datatable](https://github.com/primefaces/primevue/blob/master/packages/primevue/src/datatable/DataTable.d.ts).

Can this issue be reopened or should I create a new issue?
