### ISSUE TITLE
Toast: How to use Toast in Pinia

### ISSUE THREAD

**Issue by themodernpk** [primefaces/primevue#2790]
### Describe the bug

How to use Toast in Pinia Store

### Reproducer

https://codesandbox.io/s/kind-morning-bz41xc?file=/src/App.vue

### PrimeVue version

3.12.4

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Browser(s)

Chrome 90

### Steps to reproduce the behavior

Click on the button

### Expected behavior

Toast should be visible

**Comment by tugcekucukoglu** [comment]
Please use Discord or forum for the questions. It's not a valid issue ticket.

**Comment by corepay** [comment]
ugggh - another login on another service (discord) sucking our personal details and data with an absolute horrible UX for troubleshooting to find an answer to a question that should be documented or simply answered here as ' not doable'

What is it with you techsters and using discord gaming chat server anyway?  Is it because that's what everyone else does or is there some secret that makes this an invaluable community and tech support forum?
