### ISSUE TITLE
DataTable: When responsiveLayout is 'stack', paginator width does not scale alongside datatable

### ISSUE THREAD

**Issue by chriscsq** [primefaces/primevue#2795]
### Describe the bug

https://codesandbox.io/s/mutable-wildflower-z9outi?file=/src/DataTableDemo.vue

For the `datatable` when the `responsiveLayout` is set to `stack`,  the `paginator` width does not scale down accordingly with the rest of the `datatable` on certain screen sizes. As you resize browser window, the `paginator` width  becomes misaligned with the width of the `datatable` until you reach the responsive breakpoint to switch to a `stack` view. 

![image](https://user-images.githubusercontent.com/16171548/180084335-f646be00-6e16-4cd9-819f-3d1e72f0dd37.png)

### PrimeVue version

3.15.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Scroll to the bottom of the table and observe the behavior of the paginator background as you resize the window to its responsive breakpoint

### Expected behavior

Paginator width should be consistent with the width of the datatable

**Comment by tugcekucukoglu** [comment]
Paginator and header render correctly. When the DataTable's responsiveLayout mode is not scrollable, according to DataTable size could not fit the box.  For example [https://codesandbox.io/s/small-worker-s3p9or?file=/src/DataTableDemo.vue](https://codesandbox.io/s/small-worker-s3p9or?file=/src/DataTableDemo.vue)

For this use case, `breakpoint` attribute could be used. But it still can't be guaranteed because page breakpoints and DataTable size still have to be considered.
