### ISSUE TITLE
Button: NuxtLink and to property

### ISSUE THREAD

**Issue by Extarys** [primefaces/primevue#3118]
### Describe the feature you would like to see added

We should be able to use a Button as a link to another webpage easily.

### Is your feature request related to a problem?

Adding `p-button p-component p-button-secondary` classes to a `NuxtLink` works for the main colour, but no hovering or clicking effect is added to the link. Coming from WindiCSS (I wanted components I didn't have to build myself), the limitation is a bit frustrating.

### Describe the solution you'd like

Add a `to` property to the button, doing so should convert the `button` tag to a proper Vue/Nuxt link and apply the same styling effect.

### Describe alternatives you have considered

Maybe add a specific class we can add to `NuxtLink` to then mimic the button style.

### Additional context

Buttons are useful to get user's attention. At the bottom of a card is the most common example.
Using `to` with NuxtLink prefetch the route.

**Comment by patrickschroeter** [comment]
We have the same issue in our projects right now. I found a previous issue about a similar topic [here](https://github.com/primefaces/primevue/issues/1920).
Unfortunately the proposed workaround to wrap a button in a router link generated invalid HTML and thus is not good practice.

**Comment by ddanier** [comment]
Some background from my side and my use case:  
Having `<a href=...>` is important if you want to allow users to do stuff like right click -> open in new tab/window. I know single page applications tend to ignore this, but nevertheless this is a good and not so uncommon standard.

Wrapping the `<button>` inside an `<a>` will produce invalid HTML according to the W3C standards. This is due to the rule that interactive elements cannot be nested. The `<button>` is interactive for sure, the `<a>` element will be seen as interactive once you add an `href` attribute. So those two cannot be nested.

Other frameworks like bootstrap allow you to define something like having an `<a class="button">...</a>` to have a normal `<a>` styled as a button which fixes this issue. Hope Prime can provide something similar.

**Comment by tommie** [comment]
A comment on #3552 suggests that the `pt` property can be used to set `href`. I'm not sure adding `href` to a button makes any sense. What am I missing?

It seems this is largely a theme problem. Most button CSS selectors handling interactivity look like

```css
.p-button:enabled:hover { ... }
```

I'm guessing that `a` elements are never enabled: https://html.spec.whatwg.org/multipage/semantics-other.html#selector-enabled

Couldn't this just be changed to e.g.

```css
button.p-button:enabled:hover, .p-button:not(button):hover { ... }
```

or something similar? I.e. the theme API doesn't recognize anything but buttons as "disableable". The list of elements from the HTML spec is

>> button, input, select, textarea, optgroup, option, fieldset

I can only see a use for `.p-button` on `button` and possibly `input`, so perhaps

```css
button.p-button:enabled:hover, input[type="button"].p-button:enabled:hover, .p-button:not(button):hover { ... }
```

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.

**Comment by tommie** [comment]
I just realized that if `.p-button:enabled` is replaced with `.p-button:not(:disabled)`, this should be enough to work with all elements. No need to list multiple kinds as I suggested above.

**Comment by JPustkuchen** [comment]
Same issue in Menu components. Any solution for NuxtLinks? `to:` and `url:` don't seem to work as expected.
