### ISSUE TITLE
Custom Sorting for Table and TreeTable

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primevue#323]

**Comment by welcome14** [comment]
Hi, can i use the custom sort on my datatable column ? how ?

**Comment by FabianTe** [comment]
Hi! We are also missing this feature quiet a bit. We use the DataTable to display search results from Elasticsearch and therefore must forward sort parameters to backend search requests (similar to how it is already possible to get column filters).

**Comment by zenc0dr** [comment]
Hello. The feature never showed up?

**Comment by michaelmok2021** [comment]
Hello any update on this feature?

**Comment by tsofist** [comment]
Any updates? 🙏

**Comment by arielkuzminski** [comment]
Any updates? I need to sort my DataTable also by `selectionMode="multiple"` checkboxes.

**Comment by vrusua** [comment]
Useful feature, are there any updates, or? Thanks!

**Comment by AniaKru95** [comment]
Waiting for update

**Comment by arielkuzminski** [comment]
+1

**Comment by levitin** [comment]
Another simple use case:

Imagine, these numbers would be the content of the column to be sorted:
[2, 0, -1, -3] 

The standard sort mechanism would work like following:
* ASC: [ -3, -1, 0, 2]
* DESC: [2, 0, -1, -3]

but what if you need to sort the numbers according to their modules (also, deviation from 0)? For example:
* ASC [0, -1, 2, -3]
* DESC [-3, 2, -1, 0]

Please provide a possibility to pass a custom sorting function.

**Comment by Rakasch** [comment]
@levitin 
Someone told me that it is now possible to pass a function.
At least the documentation states `sortField - string | Function`.
I haven't tried it yet, but maybe it's already working.

**Comment by lakkvak** [comment]
Any updates?  😢

**Comment by rodrigo-guinea** [comment]
:(

**Comment by DmitrySkibitsky** [comment]
I still don't understand how I can override the sorting by a certain column and make a separate request to the backend which will load the data of the current page. 



https://github.com/primefaces/primevue/assets/20288556/1ad4a6f7-f0fe-4755-acdd-4c9fcf2c069b


![image](https://github.com/primefaces/primevue/assets/20288556/7d404b79-27f5-458a-a555-c77b4a2415e2)

**Comment by vimalrajm** [comment]
I used `lazy: true` prop to stop the default sort provided by the DataTable and used @sort event to write custom sort and send the result to the table value prop.

**Comment by ye-ole-dev** [comment]
Hej all,

I stumbled upon this issue since I needed to implement this myself. And I think @Rakasch is correct [here](https://github.com/primefaces/primevue/issues/323#issuecomment-1513679842).

The docs however could be updated to include an example on how to use the `sortField: Function` option.

I'll share my insight here, maybe it helps some folks out :-) 

I'll try to use @levitin example from [above](https://github.com/primefaces/primevue/issues/323#issuecomment-1513021440).

For example data `data = [-1, -3, 0, 2]` to be sorted by the difference from 0 you would need
```
<Column
  ...
  :sort-field="(event) => onSort(event)"
>

...

function onSort(event) {
  // event is the whole table data for this "entry" / "row" (when using objects as table data) 
  return math.abs(event);
} 
```

Another example (my use case - abstracted) is to sort specific values "A", "B", "C", "D" in a specific (non-alphabetic) way (e.g. "B", "A", "D", "C") - __because, why not?! :see_no_evil: 

```
const tableData = [
{
  sortValue: "A",
  // more data optional
},
{
  sortValue: "B",
  // more data optional
},
{
  sortValue: "C",
  // more data optional
},
{
  sortValue: "D",
  // more data optional
}
]

...

<Column 
  ...
  :sort-field="(event) => onSort(event)"
>

 ...

function onSort(event) {
  // there might be more clever ways to do this, but for the example this should do the trick
  const sorting = ["B", "A", "D", "C"]

  return sorting.findIndex(event.sortValue);
}

``` 

In brief:
the `:sort-field` function gets the data of the "row to sort" and expects a return value, that can be used to sort lexically. (At least thats my understanding)

**Comment by cagataycivici** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.

**Comment by incutonez** [comment]
I still don't think this has actually been implemented.  I'm pretty sure sortField is what it means, just a field you'd like to sort by, not an actual sort function, like what PrimeReact has.  The problem you have with sortField is that the function does not pass in the record set... it only passes in that row's record.  Also, the return value of sortField must be a string, whereas a sort function should return -1, 0, or 1.  It also seems like you can't override the [sort event](https://primevue.org/datatable/#api.datatable.emitsoptions.sort) in the DataTable, so I'm a little lost on how to accomplish a true custom sort.

**Comment by AdamVerner** [comment]
@incutonez I had some troubles figuring out how to implement custom sorting as well, the documnetation does not really mention it, but this [comment](https://github.com/primefaces/primevue/issues/323#issuecomment-1668894915) pointer me in the right direction.

Could we get a section on this into the docs? @cagataycivici 

Here is an example to sort a column by a second letter, instead of "alphabetically" (which could also be implemented by `:sort-field`, but that is not the point here. )

```vue
<script setup>
const example_items = [
  { name: 'John', city: 'New York' }, 
  { name: 'Thomas', city: 'Los Angeles' },
  { name: 'Jane', city: 'Chicago' },
  { name: 'Alice', city: 'San Francisco' },
  { name: 'Billy', city: 'Seattle' },
];

const items = computed(() => {
  if (sortField.value === 'name') {
    return example_items.slice().sort((a, b) => {
      return (a.name.charCodeAt(1) - b.name.charCodeAt(1)) * (sortOrder.value ?? 1);
    });
  }
  return example_items;
});

const sortField = ref<string>('');
const sortOrder = ref<number | undefined>(undefined);
</script>

<template>
  <DataTable
    v-model:sort-field="sortField"
    v-model:sort-order="sortOrder"
    :value="items"
    lazy
    removable-sort
  >
    <Column field="name" header="Name" sortable />
    <Column field="city" header="City" />
  </DataTable>
</template>

```

**Comment by MelentQ** [comment]
up
