### ISSUE TITLE
DataTable: Selection + Paginator

### ISSUE THREAD

**Issue by account00001** [primefaces/primevue#3477]
### Describe the bug

When using the DataTable with multiple selection checkboxes and pagination, selecting the checkbox in the header incorrectly selects every row across all pages, instead of only selecting visible rows on the current page. Is this a design choice, or unintentional? The current behavior goes against pre-existing standards. For example G-Mail will select emails only on the current page you are on, and has an additional option to select all across all pages. Am I missing an option somewhere to specify selection behavior? I couldn't find anything in the documentation.

### Reproducer

https://codesandbox.io/s/wizardly-burnell-9gn53w?file=/src/App.vue

### PrimeVue version

3.15.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

Select the checkbox in the header. Observe every row across all pages is selected instead of only the rows on the current page.

### Expected behavior

When selecting the checkbox to select all on a DataTable with pagination, only the current page's rows should be selected. When I go to a new page, no rows should be selected. When I go back to the original page, my selection should remain. If I select more items on the second page they should be additive to my current selection.

**Comment by mertsincan** [comment]
Hi @account00001,

I think you want to have selectionPageOnly attribute like in https://www.primefaces.org/primereact/datatable/selection/ (Page-Only Selection demo)

**Comment by galilmori** [comment]
You can use something like
 ```
  v-bind:select-all="allSelected"
  @select-all-change="onSelectAllChange"
```

and select ony wat you wish with the select all checkbox

here is an example:
https://codesandbox.io/s/funny-browser-s5l4rl?file=/src/App.vue

I am aware that it is not complete and you need to figure out how many rows you have in a page and which page are you in
in order to complete it but it should be feasable.

**Comment by mertsincan** [comment]
Hi,

Please see my article; https://dev.to/mertsincan/handling-big-data-on-datatable-with-checkbox-selection-multiselect-4hgc
I tried to explain this.

Best Regards

**Comment by perexwi** [comment]
Hi everyone, I know this is **_closed_** and marked as _**completed**_, but none of the approaches proposed here and in other related issues work the way I want, so I'm sharing my approach to use until the developers add **_selectionPageOnly_** to **_Primevue_**.

In my case I want to select all the visible elements whether the datatable is loaded full or lazy. Also, the behavior I expect (when all the items are selected) is that if the visible items do not match both in order and in the items themselves after performing filtering, sorting, changing pages or changing the items shown by page, all selected items must be deselected and of course the select all checkbox must be deselected as well.

```javascript
<script setup lang='ts'>

// ...imports

let visibleItems = []
const selectAll = ref(false)
const selectedItems = ref([])
const first = ref(0)
const rows = ref(25)

const onValueChange = (event) => {
    // Only store the visible items, we dont want all the items, so slice...
    const newVisibleItems = event.slice(first.value, first.value + rows.value)

    if (JSON.stringify(newVisibleItems) !== JSON.stringify(visibleItems)) {
        selectAll.value = false
        selectedItems.value = []
    }

    visibleItems = newVisibleItems
}

const onSelectAllChange = (event) => {
    selectAll.value = event.checked
    if (selectAll.value) {
        selectedItems.value = visibleItems
    } else {
        selectedItems.value = []
    }
}

const onRowUnselect = () => {
    selectAll.value = false
}

const onRowSelect = () => {
    selectAll.value = selectedItems.value.length === visibleItems.length
}
</script>
<template>
    <DataTable ...all other props
        v-model:selection="selectedItems"
        v-model:first="first"
        v-model:rows="rows"
        :selectAll="selectAll"
        @select-all-change="onSelectAllChange"
        @row-select="onRowSelect"
        @row-unselect="onRowUnselect"
        @value-change="onValueChange">
    </DataTable>
</template>
```

And that's exactly what I needed. But there is a behavior that perhaps not everyone wants and that is that with this approach if there is only one page, everything is selected and a sort is done, the items are deselected, because a comparison of a JSON string is made between both sets of items. To avoid this and keep the items selected, you can change the onValueChange function to something similar to this:

```javascript
const onValueChange = (event) => {
    const newVisibleProducts = event.slice(first.value, first.value + rows.value)

    if (newVisibleProducts.length !== visibleProducts.length || !newVisibleProducts.every(product => visibleProducts.includes(product))) {
        selectAll.value = false
        selectedProducts.value = []
    }

    // Old if
    // if (JSON.stringify(newVisibleProducts) !== JSON.stringify(visibleProducts)) {
    //     selectAll.value = false
    //     selectedProducts.value = []
    // }

    visibleProducts = newVisibleProducts
}
```

And of course you can now establish the desired behaviors by making comparisons in the onValueChange function or any other of the emits provided by the datatable and using the visible elements.

I hope this helps someone with the same "problem" :wink:

**Comment by tbredillet** [comment]
Or if you just want disable the "select all" button : 

```
.p-datatable-column-header-content .p-checkbox.p-component {
    display: none;
} 
```
