### ISSUE TITLE
Calendar: Float label defect

### ISSUE THREAD

**Issue by tugcekucukoglu** [primefaces/primevue#3546]

**Comment by Daybringer** [comment]
Float label is defecting on Firefox. Working correctly on Chromium.
![defect](https://github.com/primefaces/primevue/assets/44302901/240972f0-6f65-47e2-992a-a78f001a8ea2)

**Comment by Sector6759** [comment]
Float Labels are supported in the current Firefox but they are not in the current Firefox ESR which is based on Firefox 115 released on July 4, 2023. This is because Float Labels use the rather new [:has() CSS pseudo-class](https://developer.mozilla.org/en-US/docs/Web/CSS/:has). Firefox supports this feature starting with version 121. As Mozilla releases a new ESR about every 12 months, a new ESR should be right around the corner.

**Comment by tugcekucukoglu** [comment]
Added with version 4.
