### ISSUE TITLE
DropDown: Default Selection isn't showing

### ISSUE THREAD

**Issue by PythonDevOp** [primefaces/primevue#3557]
### Describe the bug

Dropdown will not fill with pre-selected item. I am trying to use a pre-selected option by default and then update it, but the dropdown shows up empty.

Example is in the codesandbox link

### Reproducer

https://codesandbox.io/s/modern-bird-50w8cq?file=/src/App.vue

### PrimeVue version

3.21.0

### Vue version

3.2.45

### Language

TypeScript

### Build / Runtime
Vue3 with Vite
`npm create vite@latest`

**Comment by mertsincan** [comment]
This is an expected behaviour. Firstly, the selected value must be in the `options` array. And then;
1. option -> If you use optionValue attribute, you have to set the initial value like; 
`const selected = ref("bar");`

2.option -> If you don't use optionValue attribute, you can set initial value like;
`const selected = ref({ name: "foo", value: "bar" });`

Exp; https://codesandbox.io/s/nostalgic-panka-evbuh2?file=/src/App.vue
