### ISSUE TITLE
Accordion: headerClass not working

### ISSUE THREAD

**Issue by SVANNER** [primefaces/primevue#3573]
### Describe the bug

Hi, 

I tried to use the headerClass property on the AccordionTab, I just tried to change the color text to red, but the color is not changed. The class passed to headerClass seems not to be applied.

### Reproducer

https://codesandbox.io/s/cocky-goldberg-gwkrzk?file=/src/App.vue

### PrimeVue version

3.18.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Paste the sample code of accordion from the PrimeVue website and add `headerClass="myheader` to the AccordionTab:
```
<Accordion>
  <AccordionTab header="Header I" headerClass="myheader">
        Content
    </AccordionTab>
    <AccordionTab header="Header II">
        Content
    </AccordionTab>
    <AccordionTab header="Header III">
        Content
    </AccordionTab>
</Accordion>
```

2. define the style 
 ```
.myheader {
        color: red;
    }
```

### Expected behavior

"Header I" colour changed to red.

**Comment by DenizMOz** [comment]
AccordionTabs are created programmatically in the Accordion class with a v-for loop. The name of the ''myheader'' class is passed and applied, but the styling class itself stays in App.vue, which is not part of the root path for AccordionTab. AccordionTab has another prop called "headerStyle" for this purpose.

**Comment by SVANNER** [comment]
Thanks a lot ! I'll try that !

**Comment by tugcekucukoglu** [comment]
Thanks @DenizMOz for a great explanation. `headerStyle` could be another solution, accordion header element has inner child and in your case  in scoped style, you could use like this

```
::v-deep(.p-accordion .p-accordion-header.red) {
    .p-accordion-header-link {
        color: red;
    }
}
```

**Comment by inunez-vex** [comment]
I wanna raise a little thing that I have discovered on this regard. When using eslint, it auto-corrects prop names to kebab-case (vue/attribute-hyphenation) and it converts 'headerClass' to 'header-class'. And since the tabs are created programatically, I assume it only looks for 'headerClass', therefore not applying it. It would be interesting if it could be implemented so that it uses both cases.

**Comment by timyourivh** [comment]
What @inunez-vex says seems to be the case.
@tugcekucukoglu I suggest allowing both cases since it does not conform with the default [Vue eslint plugin rules](https://eslint.vuejs.org/rules/attribute-hyphenation.html#vue-attribute-hyphenation) and thus will conflict with coding styles:

![image](https://github.com/primefaces/primevue/assets/60601502/a6e4fc13-f26a-4d27-a732-2cf6c10c301d)

---

#### Also related:

I tried property (in camel case) but it doesn't yield expected results. If I want to change the background color for one of the headers using `bg-red-500` it will look like this:

![image](https://github.com/primefaces/primevue/assets/60601502/9d77d0e4-1af0-45d5-8c2a-187e858bfa03)

---

Here is a sandbox displaying both issues:

https://codesandbox.io/s/primevue-accordion-tab-header-class-bug-z3dnln?file=/src/App.vue

If no action is taken I will create new issue(s) to address these issues separately
