### ISSUE TITLE
TreeSelect: Enhancements of component

### ISSUE THREAD

**Issue by havist** [primefaces/primevue#3659]
### Describe the feature you would like to see added

**TreeSelect** component differs from other select components (e.g. MultiSelect or Dropdown). It would be very handy to have the same possibilities on TreeSelect component like templating of tree node (item), filtering, etc. Tree component embedded inside TreeSelect component supports them.
First of all, item templating should be supported. Naive implementation can be as follow:
```html
<div class="p-treeselect-items-wrapper" :style="{ 'max-height': scrollHeight }">
    <TSTree ... >
        <template v-for="(_, name) in nodeTemplates" v-slot:[name]="slotData">
            <slot :name="name" v-bind="slotData" />
        </template>
    </TSTree>
    ...
</div>
```
where ```nodeTemplates``` are filtered TreeSelect slots, that are not ```value, indicator, header, empty and footer``` ones used in TreeSelect itself.

**Comment by tugcekucukoglu** [comment]
Definitely agree. Added on the roadmap.

**Comment by adamndev** [comment]
+1 please!

**Comment by KnifeFed** [comment]
Hello! I have a need for a TreeSelect with checkboxes and filtering, and so I found this issue. I have no idea if this is planned for anytime soon, but otherwise, am I correct in assuming it would work the same way to use the regular Tree component, enable checkboxes + filtering, and put it in a select/dropdown? I just started out using PrimeVue and I really like it so far, so thanks for everything!

**Comment by petitkriket** [comment]
+1

**Comment by estradamarkie** [comment]
Just to add to this, the other tree component has filtering feature. Maybe it's good to add it here too? Hoping this is still in the pipeline of updates.

**Comment by DBolderman** [comment]
Any news on this issue? It's assigned almost a year ago.

**Comment by tugcekucukoglu** [comment]
The new TreeSelect is: https://primevue.org/treeselect
