### ISSUE TITLE
Password: toggleMask icon CSS broken in v3.27.0

### ISSUE THREAD

**Issue by colinatwork** [primefaces/primevue#3912]
### Describe the bug

We are using the toggle mask feature and when we updated from v3.26.1 to v3.27.0, the eye icon has moved from being inside the text box to being outside. Screen shots attached where the only change was the Prime Vue version. We are using the Atlantis template as well with prime flex v3.3.0 and prime icons v6.0.1.

v3.26.1 password component:
![Screen Shot 2023-04-28 at 1 10 28 PM](https://user-images.githubusercontent.com/106704020/235223341-7177fc18-18fc-4b03-a366-3c24cd98b535.png)

v3.27.0 password component:
![Screen Shot 2023-04-28 at 1 11 20 PM](https://user-images.githubusercontent.com/106704020/235223423-ed0586ba-105c-4b61-88bf-a8056e6abf80.png)

### Reproducer

N/A

### PrimeVue version

3.27.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Expected behavior

Icon to appear inside the password text box.

**Comment by tugcekucukoglu** [comment]
How can I replicate the issue? Here is a working example https://stackblitz.com/edit/f5qpsx?file=src%2FApp.vue

**Comment by nitz25** [comment]
I have the same issue, I recently update my nuxt version to nuxt 3.5.0 with "primeicons": "6.0.1" and "primevue": "3.20.0".

<img width="412" alt="Screen Shot 2023-05-17 at 8 13 46 AM" src="https://github.com/primefaces/primevue/assets/16550197/387c28ad-0908-4ed0-989a-d544a067d697">

**Comment by theunsa** [comment]
hi @tugcekucukoglu 

i'm getting similar behaviour to @nitz25 when using nuxt3 and primevue

example with issue: https://stackblitz.com/edit/github-zglqtx?file=app.vue

**Comment by mertsincan** [comment]
Which Atlantis version are you using?

**Comment by justinrlle** [comment]
We had the same issue and we fixed it, here is my understanding of the situation:
- the `Password` nows inline the mask icon
- we had a custom built `primevue` theme which wasn't updated in a while

The custom `primevue` theme positioned the icon like any `.p-input` by using the following selector: `.p-input-icon-right > i:last-of-type`, but because now the `Password` component doesn't use anymore an icon from `primeicons` by default, the selector doesn't apply.

Here is the pretty-formatted diff of the change we did to our `theme.css`.
```diff
- .p-input-icon-right > i:last-of-type {
-   right:.5rem;
-   color:#bababa
- }
+ .p-input-icon-right > i:last-of-type, .p-input-icon-right > svg:last-of-type {
+   right:.5rem;
+   color:#bababa;
+ }
```

Also, from reading the code, it looks like setting the properties `show-icon="pi pi-eye" hide-icon="pi pi-eye-slash"` on the `Password` component would fix the issue by forcing the use of `primeicons`, letting the old selector apply.

Hope it helps!

**Comment by theunsa** [comment]
thanks for the info @justinrlle

your `show-icon="pi pi-eye" hide-icon="pi pi-eye-slash"` workaround does indeed solve the issue for me with nuxt3

**Comment by adrianrudnik** [comment]
Just had the same issue. Tried the password control with toggle mask in the theme I bought, everything seemed OK, but inside a normal Vue app it left-aligned the eye symbol. Code inspect showed that the template `prestige-vue-4.0.0` uses `primevue@3.26.1` as locked version, while my own uses `primevue@3.31.0`.

Would be great if templates could be kept at somewhat the same latest primevue version.

**Comment by tugcekucukoglu** [comment]
> hi @tugcekucukoglu
> 
> i'm getting similar behaviour to @nitz25 when using nuxt3 and primevue
> 
> example with issue: https://stackblitz.com/edit/github-zglqtx?file=app.vue

A PrimeVue theme needs to be imported or if you don't prefer it, you need to make sure Password component styles sync with the latest version.
