### ISSUE TITLE
DataTable - filtering calculated column values

### ISSUE THREAD

**Issue by juampiq6** [primefaces/primevue#401]
It would be amazing to add an specific column calculated value, based on the value of other column. I've already did that, but my problem is that filtering cant be performed, because I couldn't pass a function (which calculates the value based on other value) to a Column tag.
In my example, I have a date value on the dataset, and I want to show an "state" value, based on that date (compared to right now, there are 3 states: "Pending", "Complete", "In execution"). The showing part in a column works perfectly with template and slotProps, but the filtering of the 3 different values of "state" is the part I cant accomplish. 
Any suggestion is welcomed.

**Comment by cagataycivici** [comment]
Please use forum for questions and discussions.

https://forum.primefaces.org/viewforum.php?f=110

It sounds interesting but not sure how we can incorporate it, sounds like something that should be done on your end, maybe with custom filtering.

**Comment by guanzo** [comment]
The problem is custom filtering doesn't work without an explicit "field".

This code tries to find the data value based on a `columnField`

https://github.com/primefaces/primevue/blob/1e81630ee376585e94e983e1e3894f3bb5c54746/src/components/datatable/DataTable.vue#L596-L605

For computed columns, an explicit field doesn't exist, so `dataFieldValue` resolves to undefined. An easy solution would just be to pass the entire row data to the filter function, so the computed column can be recomputed, and then filtered.

**Comment by zsuzsmuzs** [comment]
@cagataycivici
Is there any chance you will reopen this issue? This would really be a great feature as it is impossible to filter a computed cell right now.

I would prefer version 1 from guanzo but would be happy with version 2 as well.

Thanks!

**Comment by turboteddy** [comment]
@cagataycivici , I agree with  @zsuzsmuzs . Option 1 would definitely be preferable: "**Pass the row data to the filter function**..."
