### ISSUE TITLE
DataTable: Multiple Column sorting with lazy datatable does not work

### ISSUE THREAD

**Issue by AniaKru95** [primefaces/primevue#4135]
### Describe the bug

I have lazy datatable with backend sorting and filtering.
If I assign multiSortMeta initially, sorting works properly. Icons (1,2,etc) appear in header.
Unfortunately I cannot add new column to sort, everything has been cleared.

### Reproducer

https://codesandbox.io/s/primevue-demo-forked-xj7m9h?file=/src/App.vue

### PrimeVue version

3.30.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. Create variable sortingFields with initial ref array value. (works ok)
2. Click on another column to add multiple sorting
3. Event onSort has been called, with $event parameter
4. Parameter event.multiSortMeta - contains only one (clicked column)
5. Push this clicked column to  sortingFields
6. Variable sortingFields has appropriate value but sorting icons have been reset.

### Expected behavior

My backend returns sorted dataset, but I cannot see on UI, that it has been sorted.
Props :multiSortMeta, should reacts for changing variable: sortingFields and based on this fields, display appropriate sorting icons.

**Comment by AniaKru95** [comment]
I see that, if I add key to datatable component
```
<DataTable :key="tableKey" ... />
```
and then in function onSort
```
sortingFields.value.push(...event.multiSortMeta)
tableKey += 1
```
Filters will be added properly, but I do not want to reload whole table.
It seems that prop:
```
:multiSortMeta="sortingFields"
```
is not reactive?

**Comment by mertsincan** [comment]
Hi,

Do you use `cmd` key + click combination to sort a new column? https://primevue.org/datatable/#multiple_sort
Your sample works fine for me. So, for now closed. If the problem persists, please reopen this issue. Thanks a lot for your understanding!

Best Regards,

**Comment by anchan42** [comment]
I am learning to use Vue and also PrimeVue and come across this.
I believe I might have some answers.

- Use ctrl+click to add a sort field like Mertisincan suggested
- Use v-model:multiSortMeta="sortingFields" instead of :multiSortMeta="sortingFields". This will make the binding go both ways.

See the code sandbox below. I added a button the make changes to sortingFields. When to button is clicked the table sorting will be updated. When the sorting icon on the table changed, sortingFields changed accordingly. I think this is what you meant by being reactive. 
[Code example](https://codesandbox.io/p/devbox/primevue-demo-forked-ffwsdn?file=%2Fsrc%2FApp.vue)

**Comment by pmuren** [comment]
@anchan42 That code example was super helpful.
Especially
`const sortingFields = ref([{ field: "color", order: 1 }]);` and
`<DataTable . . . sortMode="multiple" v-model:multiSortMeta="sortingFields">`

How did you figure out the expected shape of the multiSortMeta property? Now that I know what to look for, I see it in the [DataTable definition](https://github.com/primefaces/primevue/blob/master/components/lib/datatable/DataTable.vue), but I didn't see it in any docs.

Thanks again for sharing code!
