### ISSUE TITLE
Datatable: Menu Filter Icon Click Causes Column to Sort

### ISSUE THREAD

**Issue by fireblazer9** [primefaces/primevue#4268]
### Describe the bug

A bug was introduced in 3.32.0 whereby when using sortable columns, and filterDisplay="menu", clicking on the filter menu icon within the column header causes the column to sort at the same time. This can be seen in the examples on the documentation, or in the included reproducer (taken from the Samples > Customers section).

In 3.31.0 the icon can be pressed and the menu appears without causing the column to sort. 

### Reproducer

https://codesandbox.io/s/vlcj8x

### PrimeVue version

3.32.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. Add a Datatable with a column that is sortable
2. Add a filter with filterDisplay="menu"
3. Click the filter icon to display the menu
4. The table will sort at the same time

### Expected behavior

As per 3.31.0 the filter menu box should appear without the column being sorted at the same time.

**Comment by leecraigjeffries** [comment]
This is still an issue, I don't know why it is classed as fixed

**Comment by nate-watkins** [comment]
I believe this happens when the click event happens on the 'path' element within the svg. The event handler errantly passes the [isClickable](https://github.com/primefaces/primevue/blob/775ec53cbdf953f8f2c87d4d4c7966cf65b01191/packages/primevue/src/datatable/DataTable.vue#L550) check because the parent element is `svg` instead of [button](https://github.com/primefaces/primeuix/blob/6d16c216f0fc8cb3d68498d199cc1e20aab038b4/packages/utils/src/dom/methods/isClickable.ts#L13). 
In my project, I handled this by setting `pointer-events: none` via the passthrough api on the Column's `filterMenuIcon`
