### ISSUE TITLE
Image: `image` passthrough option does not work

### ISSUE THREAD

**Issue by Neluji** [primefaces/primevue#4365]
### Describe the bug

When using Pass Through on `Image` component, the `image` key does not seems to have effect on the underlying `<img>` DOM element.
> Looks like it has been introduced in PrimeVue version `3.32.1`

### Reproducer

https://stackblitz.com/edit/idru1f-nxw87x?file=src%2FApp.vue

### PrimeVue version

3.32.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Tested on Firefox 116.0.3

### Steps to reproduce the behavior

Wait & see

### Expected behavior

Both images should be blurred (the `blur` class should have been applied to `<img>` DOM element of the left image, as it is applied to the root element of the right one)

**Comment by simon-b64** [comment]
I've just encountered the same issue. Passthrough by itself does work but only the class attribute is overwritten.

As far as I can see this was the change that introduced the bug:
![image](https://github.com/primefaces/primevue/assets/47189894/0d4acee6-5d67-4b8b-b626-9e91977de343)
The problem now as far as I can see is that we now have an array inside the class attribute which when nothing is applied is empty but still there so that the class attribute is effective and cannot be overwritten by v-bind and the passthrough attributes. :)

Hope this helps to solve the issue faster ^^

**Comment by Neluji** [comment]
[Last version](https://github.com/primefaces/primevue/releases/tag/3.34.0) seems to fix this, could you test & confirm this @simon-b64 ?

**Comment by simon-b64** [comment]
Yes seems to be fixed ^^ Very nice. Thx :)

**Comment by mertsincan** [comment]
Thanks a lot for the update!
