### ISSUE TITLE
New `@layer` implementation

### ISSUE THREAD

**Issue by tugcekucukoglu** [primefaces/primevue#4504]

**Comment by riskysciolism** [comment]
This indeed IS a breaking change! Custom CSS styles declared outside of a layer will override styles declared in a layer, regardless of specificity!

**Comment by zakainsworth** [comment]
This is very frustrating. As @riskysciolism mentioned, this IS a breaking change! The Use of PrimeVue with Bootstrap 4 is broken after this update as Bootstrap 4 does not use layers.

**Comment by Flink91** [comment]
This is a breaking change for our team too, would've been nice to see that immediately

**Comment by sven-meye** [comment]
From my point of view, this is also a **breaking change** that can have significant impacts on the organization of styling. Unfortunately, the change affects us as well. In our case, the border-radius in p-buttonset is no longer overwritten, as our previous implementation defined a general border-radius outside of a layer.

**Comment by dt-ebermudez** [comment]
Hi

How is this new feature implemented?

**Comment by cjbathras** [comment]
For those of us forced to support older browsers (my customer uses Chrome 79... don't ask why, just accept that they are waaay behind the times) this is a breaking change that took me the last two days to track down. Would be great if there was a way to toggle whether we want to use this feature or not.

**Comment by zakainsworth** [comment]
@tugcekucukoglu Do you have any response to these comments?

**Comment by philgruneich** [comment]
The @layer implementation is also breaking our project's code, with reset.css styles overriding PrimeVue styles. As mentioned before, this should be reserved to a 4.0 release instead.

**Comment by joakimc** [comment]
Same for my team regarding the `@layer` implementation. We are using our apps as children of a parent app belonging to another company, and things are breaking hard due to global styling like resets.

**Comment by milanio** [comment]
The @layer implementation is also breaking our code - we are using PrimeVue inside an app which needs to support Android 6.0. and Android System WebView (Chromium 95 based). As @layer is only supported from version Chrome 99, our app completely broke after *minor* PrimeVue update from 3.29 -> 3.47. Can this be somehow turned off?

**Comment by Anubarak** [comment]
Any way to turn that off?
It broke all our apps too. We either have to change our CSS or cannot update anymore.

Why are all complains ignored?

**Comment by riskysciolism** [comment]
For those who are still struggling. We solved our problem by explicitly assigning a layer to our own CSS styles and defining the order of the layers. I know this is annoying, but it solves the problem of overwriting. What bothers me is that this is still not marked as a breaking change.
`css
@layer owncss, primevue;

@import url('primevue/theme.css');

@layer owncss { ... }
`

**Comment by vzakharov** [comment]
I’m so glad I found this thread. It broke my mind why everything all of a sudden started being super-ugly whenever I update. (For the record, the last  normally working version for me was 3.43.0.) I still haven’t figured out how to fix this, but hopefully this thread will help. It’s mind-boggling how the team decided to make this a “minor” release.

**Comment by mattanger** [comment]
Adding another +1 to hopefully help highlight that this a BREAKING CHANGE, and there's nearly no documentation on it. 

Thanks to @matthew-dean and @riskysciolism  for the comments regarding wrapping everything in `@layer`. The fix itself didn't end up being that time consuming, but tracking down the cause was. 

It's wild that a minor version update completely breaks the styles for this many people, and there's not even a hit of the possibility. It's hard to consider using primevue in the future when things like this happen.

**Comment by FVolral** [comment]
I had to rollback to previous version. I use bootstrap 4 and it breaks everything. I tried to set my reset.css in @layer, tried many solutions, lost a lot of time with it

**Comment by FVolral** [comment]
@matthew-dean I finally managed to make it works. To do so, I had to migrate from Vue CLI to Vite in order to get rid of WebPack, which was generating a bundle that messed up the cascade layer order when in production.

**Comment by riskysciolism** [comment]
As a preliminary information and possible relief, it looks like CSS layers will be optional as of version 4.
Excerpt from the [documentation](https://v4.primevue.org/theming/styled/#specificity): "The cssLayer is disabled by default to avoid compatibility issues with 3rd party CSS libraries which requires a layer configuration for compatibility that is discussed in the next reset section."

Take this with a grain of salt as I have not yet tested this and as version 4 is still in beta, this may of course still change.

**Comment by philgruneich** [comment]
Can we remove it from v3 since it is becoming a feature in v4?

**Comment by dsldiesel** [comment]
Let's stop being polite: primevue css developers are incompetent and they didn't see this coming. 
I have my whole app broken and have no idea on how to proceed. Unfortunately there's no easy fix for all users and we need to find different solutions depending on project. This makes me blame again the developers. Updating primevue dependency is a terrible nightmare.

If there's an easy-to-adopt fix, can someone explain it better?

**Comment by FVolral** [comment]
@dsldiesel  I disagree. If the CSS developers of PrimeVue are incompetent, then why are you using their libraries? I've been in the same situation as you. Yes, it's time-consuming. Like you, I had to go back over a good portion of my application's interface to fix issues. But I also know that if I hadn't used any library at all, I would have wasted a crazy amount of time reinventing the wheel. This kind of event is the price to pay, and you're paying it for free. Don't be stingy. 

It's a breaking change, so there isn't really an 'easy way.' In the documentation, a few keys are given to solve this problem: putting the CSS reset in a layer, playing with the layer order: https://primevue.org/csslayer/. As mentioned earlier, if you're using vue-cli, you'll probably have to migrate to Vite.js. You'll have to make this migration sooner or later anyway because the vue-cli documentation itself recommends migrating to Vite.

**Comment by alex-maereanu** [comment]
So bad..  anyone found a workaround around this?

**Comment by FVolral** [comment]
> So bad.. anyone found a workaround around this?

1. If you are using Vue-Cli, migrate to Vite because Webpack can disrupt your CSS layers in production when creating the final bundle.
2. Follow the documentation on ordering CSS layers: https://primevue.org/csslayer
3. Even after that, you will likely need to rework some parts of your application. If you are extensively using PrimeVue for your interface, it won't be a major issue. If not, it will require more effort. However, if you are accustomed to CSS and your app is well-organized, it won't be too much work. I managed.

**Comment by alex-maereanu** [comment]
Thanks @FVolral! But this will still be broken on Safari < 15.4  :(

**Comment by FVolral** [comment]
why are you using a so old version of safari ?
