### ISSUE TITLE
v-if works incorrect on Column in slot

### ISSUE THREAD

**Issue by nneekkiitt** [primefaces/primevue#4517]
### Describe the bug

If TreeTable is wrapped in separate component and has <slot></slot> in it instead of columns, and columns are passed to the slot from outside, v-if is ignored.

### Reproducer

https://stackblitz.com/edit/642ras?file=src%2FApp.vue,src%2FCustomTreeTable.vue

### PrimeVue version

3.35.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

Open sandbox and notice that central column is shown empty

### Expected behavior

Central column is hidden

**Comment by tugcekucukoglu** [comment]
We can see this as a feature request rather than a bug. We plan to do this for DataTable and it can be ported to TreeTable.

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).
