### ISSUE TITLE
InputNumber: Buttons are no longer same size as input field

### ISSUE THREAD

**Issue by M-arc-O** [primefaces/primevue#4659]
### Describe the bug

I am using the Sakai template and trying to update to primevue 3.35. This breaks the input number component due to the new  approach with styles in the primevue layer. Is there a way to fix this?

Before update (primevue v3.25)
![image003](https://github.com/primefaces/primevue/assets/7105679/f78b3b5f-9ce1-4129-ac0b-c1563c84aa06)
![image004](https://github.com/primefaces/primevue/assets/7105679/4f5e9893-546d-4752-ba16-a610642cf27e)

After update (primevue v3.35)
![image001](https://github.com/primefaces/primevue/assets/7105679/953f3fc7-7970-4b0e-88fe-11c62113bc02)
![image002](https://github.com/primefaces/primevue/assets/7105679/cc0c31a1-3f4f-4346-a980-2e282483c101)

### Reproducer

https://codesandbox.io/s/primevue-create-vue-issue-template-kw9g6i

### PrimeVue version

3.35

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by tugcekucukoglu** [comment]
PrimeVue uses @layer css since version 3.35.0. For this reason, theme.css files need to be updated. Also, I have updated the Sakai with the latest PrimeVue version. And want to share Lara light blue theme file: https://github.com/primefaces/sakai-vue/blob/master/public/themes/lara-light-blue/theme.css#L292
