### ISSUE TITLE
Nuxt, PrimeVue and Formkit

### ISSUE THREAD

**Issue by Nyantekyi** [primefaces/primevue#4706]
### Describe the bug

I am trying to use these **Primevue** and **Formkit** in my Nuxt 3 application however they seem not to be compatible. Please help me out with the configuration process. Mostly **Formkit** stops working right after installing **Primevue**.

### Reproducer

https://codesandbox.io/s/primevue-create-vue-issue-template-kw9g6i

### PrimeVue version

3.8.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

**Comment by FlipWarthog** [comment]
This should probably be posted as a discussion rather than an issue, and can you include your configurations? https://github.com/orgs/primefaces/discussions

I threw together a basic setup following the guides for: Nuxt, PrimeVue, and FormKit. So far it seems compatible: https://stackblitz.com/edit/github-zq1rfw?file=nuxt.config.ts

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).
