### ISSUE TITLE
MultiSelect - add label for allSelectCheckBox

### ISSUE THREAD

**Issue by ochiers** [primefaces/primevue#481]
Hello,

When we use the multiselect without filter so we have an option with no text.

It's a good upgrade to set this text if we can have text label.

Thanks.

**Comment by johnfmorton** [comment]
This request by @ochiers is one I also share, but in addition, the option to remove the close button on this line in the dropdown would help my users.

<img width="683" alt="prime-vue-multiselect-option-request" src="https://user-images.githubusercontent.com/119723/98698397-f8453c00-2343-11eb-8969-d444b2b03364.png">

I find that the "X" causes confusion to users, and it's taken to mean "deselect all options" instead of "close this drop-down menu." The behavior is the opposite of what is expected (granted, based on only a few discussions). Having the option to add a text label next to the "allSelectCheckBox" (my choice would be _"Select All"_) and the option to exclude the close button entirely would benefit the usability of the MultiSelect drop-down.

Thanks much.

**Comment by cagataycivici** [comment]
Added to the roadmap with a high priority, thank you.

**Comment by itapingu** [comment]
Is it possible to get this done? Thanks

**Comment by sanibs23** [comment]
@cagataycivici @mertsincan,  is the feature implemented to add the label (via props) for the all select checkbox?

**Comment by davidhorak** [comment]
Is there an update on this one?

**Comment by MarcinStanczyk7** [comment]
.p-checkbox {
      &::after {
        content: "Select All";
      }
    }
    .p-multiselect-close-icon {
      &::before {
        display: none;
      }
    }

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.

**Comment by WatCodeDatCode** [comment]
Anyone coming across this in v4 and still having issues or not wanting to use css content / absolute positioned text, for me the best solution so far has been to set `showToggleAll` prop to false and duplicate the functionality inside the `header` slot by adding a readonly `Checkbox` toggling based on if selected values match length of value options. 

Here a **[quick example](https://stackblitz.com/edit/9yvkhe?file=src%2FApp.vue)**.

Downside is though that you have to essentially duplicate styling to match (if you want not just the checkbox to be clickable) and take care of matching aria labelling.

**Comment by moskalik-mg** [comment]
The problem has been there for 4 years, when will it be fixed?

**Comment by patie** [comment]
Was added with high priority 4 years ago and still not fixed.. @tugcekucukoglu https://github.com/primefaces/primevue/issues/481#issuecomment-836496844

<img width="1050" alt="Image" src="https://github.com/user-attachments/assets/c695095d-f586-4e02-bb72-e02b48584aad" />

**Comment by armandino** [comment]
+1. Please consider adding support for overriding the label. It seems to be a fairly common use case.

Thanks @WatCodeDatCode for the workaround!
