### ISSUE TITLE
Binding and ordering pt options defect

### ISSUE THREAD

**Issue by tugcekucukoglu** [primefaces/primevue#4921]
- [x] OrderList
- [x] PickList
- [x] InputNumber
- [x] Password
- [x] SplitButton

**Comment by pontsci** [comment]
Quick question, did this change how pt works for these components? I noticed when upgrading my pt needed to be updated like so:
#### Pre 3.43
```
:pt="{
    input: { class: 'bg-background p-1 border-secondary shadow-background outline-accent w-full' }
}"
```

#### 3.43
```
:pt="{
    input:{
        root:{
            class: 'bg-background p-1 border-secondary shadow-background outline-accent w-full' 
        }
    }
}"
```

Was this intentional? This was the only way I could get it to work. I noticed it was updated in the passthrough docs, so I'm guessing this was the intended use all along?
