### ISSUE TITLE
Add `attrs` param to all `pt` functions

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primevue#4951]
Details; https://vuejs.org/guide/components/attrs

**Comment by Duoliver** [comment]
Hello! I'm not sure if it's the place for asking that, but why wasn't the said attribute added to the other PTMethodOptions such as the ones of `InputText` and `Button`? I certified myself that the version I'm running is with the same `InputText.d.ts` as the one in `master` and I can see that the file wasn't updated in neither of the commits that are related to this issue. I am being able to access `attrs` in both of these components. However, for obvious reasons, it gives me a Typescript error.  I had to rely on a workaround. Is it because of some kind of good practice that I missed while reading the documentation? Thank you so far for the amazing library.
