### ISSUE TITLE
`metaKeySelection` default type is changed as `false`

### ISSUE THREAD

**Issue by tugcekucukoglu** [primefaces/primevue#4985]
The default value of `metaKeySelection` was changed to `false` according to the demand from the users. 

Components affected by this change:
- DataTable
- TreeTable
- Tree
- TreeSelect
- OrderList
- PickList
- Listbox

**Comment by lpalacecr** [comment]
Que implicaciones tiene en el código que tengo actualmente? Esto debido a que no me he podido pasar a estar versión ya que la aplicación deja de funcionar sin haber hecho ninguna modificación.
Muchas gracias...


What implications does it have on the code I currently have? This is because I have not been able to upgrade to this version since the application stops working without having made any modifications.
Thank you so much...

Translated by google translate.
