### ISSUE TITLE
Edit and Sort combination support for Table

### ISSUE THREAD

**Issue by mr83-uw** [primefaces/primevue#508]
**I'm submitting a ...**
 ```
 [x ] bug report
 [ ] feature request
 [ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```
Similar to this bug in primereact: https://github.com/primefaces/primereact/issues/878

When I add a sort field to the Demo on this page: https://primefaces.org/primevue/showcase/#/datatable/edit

When editing a cell, the datatable will change the sort of the table, and cause you to edit unintended cells. The expected behavior would be to not resort the table until the editing is completed.

Also is it possible to have a reactiveSort flag on the table, that will only resort the table when clicking on the column headers? Any new entrys in the data should default to the end of the list.

**Comment by cagataycivici** [comment]
Sort and Cell edit combination is not supported now, we'll review it after 3.0 final.

@mertsincan Also happens to React and probably NG so let's discuss this.

**Comment by subodhkalika** [comment]
+1

**Comment by mertsincan** [comment]
Hi,

Fixed for PrimeReact and PrimeVue. The DataTable component never stores the user's data. Therefore, in any state change, the sort and filter events are called again. That's why I added a callback called @ value-change to send the data that changes during these events to the user. With this callback, you can sync the calculated data with the data you give to the DataTable. Exp;

```
<DataTable :value="products" editMode="cell" @value-change="onValueChange($event)">
   ...
</DataTable>
...

onValueChange(value) {
    this.products = value;
}
```

Best Regards,
