### ISSUE TITLE
TieredMenu: Submenu is not opened at the first mouse hover

### ISSUE THREAD

**Issue by MassimoBev** [primefaces/primevue#5088]
### Describe the bug

In Tieredmenu, the submenus are not shown by mouse hover, it is needed to click on the option first  to see the suboptions. 
But after this click, the submenus are shown by mouse hover.

### Reproducer

https://primevue.org/tieredmenu/

### PrimeVue version

3.45

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Firefox, Chrome

### Steps to reproduce the behavior

1. go to a Tieredmenu
2. choose an option(for example file) with submenu
3. on mouse hover, the submenu is not showed
4. click on "file" option and the submenu is shown
5. Move focus outside submenu. The submenu is closed
6. now with a mouse hover the submenu is shown

----- 

4.a click on "file" option and the submenu is shown
5.a click again on "file" option and the submenu is closed
6.a now with a mouse hover the submenu is NOT shown

on the page "https://primevue.org/tieredmenu/" the "file" option has the suboption "new". "New" displays the submenu without having to click it first

![screenshot](https://github.com/primefaces/primevue/assets/125351453/67322814-429a-4046-87d3-129619192aae)

### Expected behavior

Submenus are always shown by mouse hover

**Comment by mertsincan** [comment]
Hi @MassimoBev, 

Thanks a lot for your report! This is by design. Most of our menu components work like this. I think we can add a new prop for it. Can you open a ticket in PrimeVue Discussions so other users can upvote?  
https://github.com/orgs/primefaces/discussions/categories/primevue

For now, closed. When there are enough upvotes, we will implement it. Thanks a lot for your understanding!
Best Regards,
