### ISSUE TITLE
Unit tests in the master branch are failing

### ISSUE THREAD

**Issue by sodatea** [primefaces/primevue#5095]
### Describe the bug

Hi, I'm working on https://github.com/vuejs/ecosystem-ci
Considering PrimeVue is such a popular library, I plan to integrate this project into the ecosystem-ci to make sure any new Vue bug fixes or features would not break PrimeVue.

However, I noticed that a few unit tests started failing since v3.45.0.
I would like to help resolve these issues so that we can run PrimeVue's tests in the ecosystem-ci.

But I'm not sure if it's the tests that are outdated or if these failures are real regressions.

### Reproducer

https://github.com/primefaces/primevue.git

### PrimeVue version

3.47.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

```
git clone https://github.com/primefaces/primevue.git
cd primevue
npm ci
npm run test:unit
```

### Expected behavior

In 3.44:

```
 Test Files  82 passed (82)
      Tests  583 passed (583)
```

In the current master branch:

```
 Test Files  7 failed | 75 passed (82)
      Tests  17 failed | 566 passed (583)
```

**Comment by mertsincan** [comment]
Hi @sodatea,

Thanks a lot for your interest! We would be pleased if you support us with PR on this issue. We are currently making improvements regarding accessibility, new features and modern styling. That's why we haven't had time to adapt the tests to them yet. We will try to fix existing tests in the core before the next version is released. Of course, you can contribute to this with PR. I want you to know that we will focus more on tests in 2024. We are trying to complete all our shortcomings step by step.
