### ISSUE TITLE
DataTable / Skeleton: Skeleton not working when the DataTable has pagination enabled

### ISSUE THREAD

**Issue by felldo** [primefaces/primevue#5113]
### Describe the bug

The DataTable has an issue with skeletons, if pagination is enabled. When enabling paginator, the skeletons do no appear anymore.

Paginator disabled:
![image](https://github.com/primefaces/primevue/assets/31566807/76ee9147-f71c-4f11-a180-b9e6a8981224)

Paginator enabled:
![image](https://github.com/primefaces/primevue/assets/31566807/baed5251-e75a-4dc4-89e6-735e3c0b9d6c)

### Reproducer

https://codesandbox.io/p/devbox/wizardly-water-n2p4ry

### PrimeVue version

3.46.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Steps to reproduce the behavior

Set `:paginator` to true for a DataTable while when it uses Skeletons

### Expected behavior

Show the Skeletons, even if the DataTable uses pagination

**Comment by mertsincan** [comment]
Thanks a lot for your report! I'll check and get back to you.

**Comment by tugcekucukoglu** [comment]
DataTable's `paginator` prop must be used with the `rows` prop. I couldn't run the demo, but if you think the problem is not solved, you can inform us.

**Comment by ayomidetobi** [comment]
I'm having issues using the loading slot in the PrimeVue `DataTable` component. Even though I've defined a custom loading template with skeleton loaders [Prime vue lazy vitualscroll](https://primevue.org/datatable/#lazy_virtualscroll) the table still shows the default loader instead of my custom one.

I want to display skeleton loaders per row/column, like in the virtual scrolling example, but with lazy pagination instead.

here is a link to reproduce [click here](https://stackblitz.com/edit/skfetarn?file=src%2FApp.vue)

current work around is using skeleton datatable
