### ISSUE TITLE
Calendar: Inline header slot

### ISSUE THREAD

**Issue by mateenagy** [primefaces/primevue#5736]
### Describe the bug

It is not really a bug, but it not make so much sense to me.

If the Calendar used with `inline` we are able to use the `header` slot. This `header` slot is kind of useless in this form because we can only append things before the built in header, but I think it's make more sense to have control for the whole header and expose the important values for control and display. 

My use case here is for example I want disable the year/month selector when the date is clicked (without the `pointer-events: none` workaround) and also to control the button visibility logic.

In the Reproducer link I linked a proof of concept update in the Calendar component. It will expose some data and events for the header which can be used while creating custom template content

### Reproducer

https://github.com/mateenagy/primevue/blob/master/components/lib/calendar/Calendar.vue

### PrimeVue version

3.52.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by tugcekucukoglu** [comment]
We cannot make this change at the moment due to backward compatibility. We will definitely consider this when adding the headless mode. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).

Thank you.
