### ISSUE TITLE
Improve PrimeVue bundle

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primevue#5774]
TODO

**Comment by sceee** [comment]
Hi @mertsincan , just wanted to let you know that your last change here ( a438dbae1eaecc42e6b692e9adeb0a658c4afff4 ) broke the possibility to test primevue components in vitest. Please see #5821 for details.

**Comment by Jacobs63** [comment]
Hi @mertsincan your change in broke this again since https://github.com/primefaces/primevue/blob/master/packages/primevue/rollup.config.mjs#L148 only generates ES Modules inside the `package.json` and therefore `main` only references an ES Module.

Can we get CJS back so that vitest could work well?
