### ISSUE TITLE
Add `as` and `asChild` property to Button

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primevue#5996]
| Prop | Default | Description
| --- | --- | --- |
as | BUTTON | Use to change the HTML tag of root element.
asChild | false | When enabled, it changes the default rendered element for the one passed as a child element.

**Comment by aeruggiero** [comment]
Hi nice feature!
I would like to suggest that it would be beneficial for the as property to accept Objects.
I am using InertiaJS, and for routing, I have to use the Link component (which translates into an anchor link but with the SPA feature otherwise disabled).

If I use <Button :as="Link" /> it works, but the console gives this error:
Invalid prop: type check failed for prop "as". Expected String with value "[object Object]", got Object

Thanks!

**Comment by mertsincan** [comment]
Thanks a lot for your feedback! Could you please create a new github ticket with sample usage?
