### ISSUE TITLE
Carousel: Index is undefined in PassThroughOptions

### ISSUE THREAD

**Issue by AdamKj** [primefaces/primevue#6264]
### Describe the bug

I am trying to access the current `index` for each item inside the PassThroughOptions since I am using an unstyled component and needing to style the component by myself.

Looking at the component style, you are using the `index` prop:
![image](https://github.com/user-attachments/assets/a584dc3e-408d-4f75-9f77-89a1d6a6c9a4)
https://github.com/primefaces/primevue/blob/master/packages/primevue/src/carousel/style/CarouselStyle.js

But when I am trying to access the `index` prop I just get `undefined`: 
![image](https://github.com/user-attachments/assets/cbfe9f39-c521-4fee-8330-cf900a07bd89)
![image](https://github.com/user-attachments/assets/43738c78-13f3-4b6e-bcbc-c680033f3c92)

Please let me know if you need more information.

### Reproducer

https://stackblitz.com/edit/2chshc?file=src%2FApp.vue

### PrimeVue version

4.0.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Run the StackBlitz project
2. Right-click anywhere on the page and click Inspect
3. Open the console and look for the console.log() including the text `index`

### Expected behavior

Accessing each index per item in the Carousel so I can style each separate item.

**Comment by WatCodeDatCode** [comment]
The `index` is undefined there because index does not exist as an option for the [item passthrough](https://primevue.org/carousel/#api.carousel.slots). It works in the main style because this is passed directly to the class "under the hood" through the BaseComponent's cx method.

Having said that, as you have illustrated, you have access to the `index` [through the `item` slot](https://primevue.org/carousel/#api.carousel.slots) itself. This can therefore be used directly within the template to dynamically apply classes or other logic based directly on the index. 

Assuming that you wanted to style similarly based on the start, end, or active item like in the base style, you can even use a :deep selector for the `data-p-carousel-item-{x}` attribute. 

Here an [updated example](https://stackblitz.com/edit/2chshc-a3stoc?file=src%2FApp.vue).

**Comment by tugcekucukoglu** [comment]
Finding a solution for PT by looking at the inner API is not the right way. It may mislead you. In the new version, you can reach the index with context.

**Comment by AdamKj** [comment]
> The `index` is undefined there because index does not exist as an option for the [item passthrough](https://primevue.org/carousel/#api.carousel.slots). It works in the main style because this is passed directly to the class "under the hood" through the BaseComponent's cx method.
> 
> Having said that, as you have illustrated, you have access to the `index` [through the `item` slot](https://primevue.org/carousel/#api.carousel.slots) itself. This can therefore be used directly within the template to dynamically apply classes or other logic based directly on the index.
> 
> Assuming that you wanted to style similarly based on the start, end, or active item like in the base style, you can even use a :deep selector for the `data-p-carousel-item-{x}` attribute.
> 
> Here an [updated example](https://stackblitz.com/edit/2chshc-a3stoc?file=src%2FApp.vue).

Thank you for the help! I opted to go with another approach, but this might be useful for other components.

**Comment by AdamKj** [comment]
> Finding a solution for PT by looking at the inner API is not the right way. It may mislead you. In the new version, you can reach the index with context.

The `context` seems to be undefined as well:
![image](https://github.com/user-attachments/assets/b05643ce-3926-472c-b828-7c4de32112b1)
![image](https://github.com/user-attachments/assets/11d3a44f-2663-48d7-bbe7-af7a32d32024)

**Comment by tugcekucukoglu** [comment]
> In the new version, you can reach the index with context.

**Comment by AdamKj** [comment]
> > In the new version, you can reach the index with context.

Sorry I don't know which new version you mean, I am using v4 in my project and I am reading the documentation for v4.
