### ISSUE TITLE
DataTable: Cannot change matchMode on `filterDisplay` = `menu`

### ISSUE THREAD

**Issue by jkowalczyk2909** [primefaces/primevue#6311]
### Describe the bug

In `filterDisplay = 'menu'` mode, you cannot change `matchMode` . For `row` mode works fine.
Throws:
```
TypeError: Cannot read properties of undefined (reading '0')
    at Proxy.onMenuMatchModeChange
```

### Reproducer

https://stackblitz.com/edit/primevue-4-vite-issue-template-znkaf6?file=src%2FApp.vue

### PrimeVue version

4.0.5

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

Try change `matchMode` on `filterDisplay` mode set to `menu`

**Comment by lucaspeeters** [comment]
Hello @jkowalczyk2909, 

I have the same error, have you been able to find a solution since?

**Comment by jkowalczyk2909** [comment]
Hi,

Not really, my project is still under development so I don't spend too much time on it. Filtering is just an additional feature. I hope it will be fixed soon

**Comment by lucaspeeters** [comment]
Ok no worries, courage for your project.

If you ever want an alternative solution for now, I use this and it seems to work: 

Instead of putting:
name: { value: null, matchMode: 'contain' },
Use:
name: { operator: FilterOperator.AND, constraints: [{ value: null, matchMode: FilterMatchMode.CONTAINS }] },

I found this thanks to this: #2658 

Have a nice day.

**Comment by dasmikko** [comment]
This is still an issue in version 4.2.2

**Comment by tugcekucukoglu** [comment]
For demo questions, you can ask for help from the community on discord or discussions.
