### ISSUE TITLE
FileUpload: maxFileSize error is not shown in template

### ISSUE THREAD

**Issue by dinacuatro** [primefaces/primevue#6404]
I am using template (https://primevue.org/fileupload/#template), and would like to access `maxFileSize` error from a method in order to show it in a toast component. Is it possible?

**Comment by dcb99** [comment]
> I am using template (https://primevue.org/fileupload/#template), and would like to access `maxFileSize` error from a method in order to show it in a toast component. Is it possible?

It would be helpful if you provided a StackBlitz or at a minimum, some code here demonstrating what you're trying to do.

**Comment by WatCodeDatCode** [comment]
The error does not show up because the custom `content` template does not pass and use the `messages` prop. 

I have created a PR that the team can decide if the example should be extended, but in the mean time take a look to see how you can implement it on your end.

**Comment by WatCodeDatCode** [comment]
It seems the only area that the info regarding these custom validations appear is within this `messages` slotProps. Since this is not an emitted function, the only way I could think at the moment to get it to work would be passing the messages to a function that sets a watched `ref` that then can loop through the messages and set the toast values. 

**[Here](https://stackblitz.com/edit/qy6p1e?file=src%2FApp.vue)** is a little proof of concept.

There is likely an even better way to do it natively, otherwise an expansion of functionality would require opening an enhancement request in [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).

**Comment by tugcekucukoglu** [comment]
It is not a core issue and you can always improve the live example yourself.
