### ISSUE TITLE
Scoped style (`dt` props) does not attach to page with correct selector

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primevue#6408]
The `attribute` selector is generated differently on the server and client.

**Comment by Sherl0ck007** [comment]
After the change in [this commit](https://github.com/primefaces/primevue/commit/335c6d862da08b6e87b89c1ef972001f66e3f754), the `pc{number}` attributes in snapshots are not consistent. The change on every run of the unit test. This causes snapshot tests to fail because of a mismatch in either the property name or the order of html props in the snapshots.
When you update the failing snapshots, the match during the very next run. The run after, they fail again because of a mismatch.
Please consider re-opening this issue to address the problem it is causing.
