### ISSUE TITLE
Select.vue - TypeError: Cannot read properties of null (reading '$el') on closing select

### ISSUE THREAD

**Issue by wijzijnweb** [primefaces/primevue#6545]
### Describe the bug

When filter is on and autoFilterFocus as well then on closing the select it wants to focus the filterInput.
But the filterInput is null.

I don't see why filterInput needs to be focused at all when closing the select.

It's caused by this line:

https://github.com/primefaces/primevue/blob/9d9ae356d07e599163a6b4b801c7a74f570a80cd/packages/primevue/src/select/Select.vue#L710

### Reproducer

https://stackblitz.com/edit/primevue-4-vite-issue-template-ajtkvm?file=src%2Fmain.js

### PrimeVue version

4.1.0

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome 129.0.6668.70

### Steps to reproduce the behavior

Open the select and close it by clicking next to it.

### Expected behavior

Not to focus the filterInput when closing the select.

**Comment by wijzijnweb** [comment]
Pull request: https://github.com/primefaces/primevue/pull/6546

**Comment by wijzijnweb** [comment]
Whoops, missed the issue here: https://github.com/primefaces/primevue/issues/6539

**Comment by tugcekucukoglu** [comment]
Duplicate

**Comment by 1Map** [comment]
I see that you changed line 691 (onOverlayEnter)

`                this.autoFilterFocus && this.filter && focus(this.$refs.filterInput.$el);`                

But the problem is actually in the onOverlayLeave

`                    focus(this.$refs.filterInput.$el);`

The focus on the onOverlayLeave can be removed as there are no need to focus on the filterInput during a leave (Does not make sense)

**Comment by wijzijnweb** [comment]
@1Map  +1. 

@tugcekucukoglu Please re-evaluate this pull-request. It's not for the same issue you think it was.

**Comment by adamreisnz** [comment]
This is still an issue, also in `onOverlayEnter`. Workaround is to not use `auto-filter-focus` when not also using `filter`.
