### ISSUE TITLE
InputMask: can't type anything into input after updating to 4.1

### ISSUE THREAD

**Issue by IgorVDubov** [primefaces/primevue#6555]
### Describe the bug

Hi, 
after updating to 4.1 from 4.0.7 when typing in InputMask no symbols appears.

### Reproducer

https://stackblitz.com/edit/primevue-4-vite-issue-template-bweifp?file=src%2FApp.vue

### PrimeVue version

4.1.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

**Comment by CCodam** [comment]
Adding the following code to the bottom of App.vue, of the stackblitz reproducer you provided, fixes your issue.
I honestly thought that a ref had always been a requirement, but apparently it wasn't for InputMask in v3 and 4.07.
I'm not sure why not though, as it's a requirement for all the other stateful components, like InputNumber, Password, SelectButton, RadioButton etc.

I'd argue that the change is towards standardization.
Do you have a specific use case, where you absolutely wouldn't want to use a ref with the component, or is it more that you see it as a breaking change?
```vue
<script setup>
import { ref } from 'vue';

const value = ref(null);
</script>
```

**Comment by CCodam** [comment]
I understand that it's a breaking change for you.
I'd have to refer to the Prime folk, whether it's by design or a something they'd want to change.

In the case that it's by design, I'd still like to try and find a solution for your specific use case.
Would the following work for you, or do you need the lazy update that the blur provide?
https://stackblitz.com/edit/primevue-4-vite-issue-template-nyeplx?file=src%2FApp.vue,src%2FinputsList.vue

**App.vue**
```vue
<template>
  <img src="./assets/primevue-logo.png" alt="PrimeVue Logo" />
  <h2 class="pt-4">PrimeVue Issue Template</h2>
  <h2 class="pt-4">
    <span class="mx-12">InputMask</span>
    <span class="mx-12">InputText</span>
    <span class="mx-10">dataArray</span>
  </h2>
  <div class="flex flex-row">
    <div class="mx-5">
      <inputsList v-model="dataArray" />
    </div>
    <div>
      <div class="my-5" v-for="(field, index) in dataArray">
        {{ field }}
      </div>
    </div>
  </div>
</template>

<script setup>
  import { ref } from 'vue';
  import inputsList from './inputsList.vue';
  const dataArray = ref([9999, 8888, 7777]);
</script>
```
**inputsList.vue**
```vue
<template>
  <div v-for="(field, index) in dataArr">
    <!-- <InputMask that don't work at 4.1 and worked at 4.07 -->
    <InputMask
      :id="index"
      class="mx-5 my-1 w-32"
      mask="9-999"
      v-model="dataArr[index]"
    />
    <!-- <same args InputText that work at 4.1 -->
    <InputText
      class="mx-5 my-1 w-32"
      :modelValue="field"
      @blur="dataArr[index] = $event.target.value"
    />
  </div>
</template>

<script setup>
  const dataArr = defineModel();
</script>

```

**Comment by IgorVDubov** [comment]
Thank you,
at that case it working (with unmask="true") - i can filter wrong with mask and don't need blur here.

**Comment by IgorVDubov** [comment]
But.....
When I try to use v-model in my app new issue appears.
my case is a little bit more complex: component shows number of values  (in my case phone numbers) by InputMask at disabled mode and when value needs to be editing I set off disabled and edit value in the same element.
But when I add unmask prop (in order to receive unmasked values at v-model) and switch disabled prop, value is disapear like it is null.
When I remove  unmask prop from InputMask all work correctly, but values passing with v-model are with mask symbols. 
ex:
https://stackblitz.com/edit/primevue-4-vite-issue-template-bweifp?file=src%2FApp.vue,src%2FinputsList.vue

When I used blur I removed mask symbols by using regexp replace and with v-model i cant receive clean values.
May be that is another issue coming from my case.

**Comment by CCodam** [comment]
> [!IMPORTANT]
> Well that's a bug.

The value is not set correctly on the DOM input element at mount.
_Somehow still available through document.getElementsByClassName('p-inputtext')[0].value and $el.value??_
![image](https://github.com/user-attachments/assets/4510e5c5-f0c9-458f-b4fd-a33857d7160a)
This is due to the **InputMask** component having to use **:value="currentVal"** for functionality instead of the usual **modelValue**.
This is only an issue when the **InputMask** component is tagged **unmask** and the **disabled** state changes, without first being interacted with.
In all other cases **isValueUpdated()** will be true, when the **disabled** state change occur, and the **updated()** function checks it, to see if it should call updateValue().

**isValueUpdated()** has the following logic.
```js
return this.unmask 
  ? this.modelValue != this.getUnmaskedValue() 
  : this.defaultBuffer !== this.$el.value && this.$el.value !== this.modelValue;
```
We could change it to something like this.
```js
return this.unmask
  ? this.modelValue != this.getUnmaskedValue() || (!this.$el.value && this.$el.value !== this.modelValue)
  : this.defaultBuffer !== this.$el.value && this.$el.value !== this.modelValue;
```
**However** while I haven't observed any other issues related to the value not being set correctly on the DOM element, we should still **consider settings currentVal on mount**.
Also, right now an **update:modelValue** is being emitted on the first **disabled** state change, which isn't necessary, and could then be avoided.

> [!TIP]
> Temporary workaround for you

- We add a **ref** to the **InputMask**, and because we're working with **v-for** it will be an array, so we'll want a **refKey**.
- We can then iterate over the array and call updateValue(), which will set the value on the DOM element.
https://stackblitz.com/edit/primevue-4-vite-issue-template-m17i2w?file=src%2FApp.vue,src%2FinputsList.vue
```vue
<template>
  <div v-for="(field, index) in dataArr">
    <!-- <InputMask that don't work at 4.1 and worked at 4.07 -->
    <InputMask
      ref="inputMasks"
      :refKey="index"
      class="mx-5 my-1 w-32 likeLabel"
      v-model="dataArr[index]"
      mask="9-999"
      unmask
      :disabled="!props.edit"
    />
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue';

const dataArr = defineModel();
const props = defineProps({ edit: Boolean });

const inputMasks = ref([]);

onMounted(() => {
  inputMasks.value.forEach((inputMask) => {
    inputMask.updateValue();
  });
});
</script>
```

**Comment by IgorVDubov** [comment]
Try that at my project - all works.
Thanks for that workaround
