### ISSUE TITLE
How to use InputText ref?

### ISSUE THREAD

**Issue by c0nd3v** [primefaces/primevue#6567]
### Describe the bug

How can I get access to HTMLInputElement using ref ?

### Reproducer

Title

### PrimeVue version

4.1.0

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by c0nd3v** [comment]
@CCodam Your example is not valid typescript.

**Comment by CCodam** [comment]
@c0nd3v This issue is not a bug. This is not a support site, it's meant for Bug reporting and Feature requests. I'm not affiliated with PrimeVue, if you want support you can find it here: https://primevue.org/support/
Sorry to be that guy, but I gave you a working proof of concept, that you should be able to make into valid TypeScript yourself.
I've updated the previous post to better adhere to TypeScript, but it's not perfect. SORRY.

**Comment by bwhitt** [comment]
Adding on here just in case it helps the next person running into this issue since I found this post running into a similar issue. I was able to find a solution by using defineExpose.

Something like: 
const myTemplateRef = ref(null);

defineExpose({myTemplateRef});

<InputText ref="myTemplateRef" />
