### ISSUE TITLE
Paginator: Responsive paginator shows all variations at same time instead of at each breakpoint

### ISSUE THREAD

**Issue by daveraynor** [primefaces/primevue#6595]
### Describe the bug

The paginator component's responsive functionality isn't working. It shows all variations stacked instead of when resizing window.

You can go to the stackblitz link from the code examples in the primvue documentation

<img width="1704" alt="Screenshot 2024-10-17 at 11 12 10 AM" src="https://github.com/user-attachments/assets/64101dde-329d-4b83-967f-8ac9be30b23e">

### Reproducer

https://stackblitz.com/edit/primevue-4-vite-issue-template-8fevuq?file=src%2FApp.vue,src%2Fmain.js

### PrimeVue version

4.1.1

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

chrome, safari, firefox

### Expected behavior

Expecting paginator to display the single component that shows each variation at different screen sizes instead of all variants stacked on the same page.

**Comment by CCodam** [comment]
This is due to the stylesheets being added in the wrong order. The highlighted one should be after the other two.
![image](https://github.com/user-attachments/assets/6f4d92fa-fb50-44c8-9169-859f81b141e1)

I'm not sure how we accomplish that. Maybe we need to wait for nextTick before calling or within the createStyle function?

Also, unrelated to this specific issue, there is syntax error in the css being generated. The "," needs to be replaced with a "{"
https://github.com/primefaces/primevue/blob/69d0407fe6aa617bfd0f0d4cb5119d3446c1bf4d/packages/primevue/src/paginator/Paginator.vue#L210

> [!TIP]
> Workaround
> https://stackblitz.com/edit/primevue-4-vite-issue-template-vgctwd?file=src%2FApp.vue

- We ref the Paginator component
- We call the createStyle() method at onMounted
```vue
<template>
<div class="card">
    <Paginator
        ref="comPaginator"
        :template="{
            '640px': 'PrevPageLink CurrentPageReport NextPageLink',
            '960px': 'FirstPageLink PrevPageLink CurrentPageReport NextPageLink LastPageLink',
            '1300px': 'FirstPageLink PrevPageLink PageLinks NextPageLink LastPageLink',
            default: 'FirstPageLink PrevPageLink PageLinks NextPageLink LastPageLink JumpToPageDropdown JumpToPageInput'
        }"
        :rows="10"
        :totalRecords="120">
    </Paginator>
</div>
</template>

<script setup>
import { ref, onMounted } from 'vue';

const comPaginator = ref();

onMounted(() => {
    comPaginator.value.createStyle();
});
</script>
```
