### ISSUE TITLE
Calendar sets date in v-model a day ago part two

### ISSUE THREAD

**Issue by tudorels** [primefaces/primevue#674]
Hello, in the first issue (https://github.com/primefaces/primevue/issues/628) I did not know some things about this issue. So I found that the issue is caused by how the time is calculated. If showtime is false, the js calculate from the hour 00:00 of date selected and finally set hour 22:00 a day ago and the date in v-model became currentdate - 1. So can you change the how date is calculated when time is not showed. The settings I have in calendar are: 
` <Calendar
              v-model="data1"
              dateFormat="dd.mm.yy"
              :manualInput="true"
              :showIcon="false"
              :touchUI="true"
            />`
I hope you manage to solve this soon. Thank you!

**Comment by cagataycivici** [comment]
Could you please provide a test case? What is your timezone? Can you replicate it on live showcase?

**Comment by juanparati** [comment]
I can also reproduce this issue. 

The problem is not the component itself but how Date object is serialized by Javascript. 

When the Date model is returned to the parent component and it's serialized in order to send it to the back-end using JSON.stringify function the date is transformed to UTC. 

See this example:
https://jsfiddle.net/x48z30n9/
(Remember your webbrowser  or computer should be configured with a timezone different than UTC).

I enclose screentshot of the issue.
![Screenshot 2020-11-26 at 09 56 33](https://user-images.githubusercontent.com/835173/100329451-f4fdb180-2fcd-11eb-9c13-1153dca1d999.png)

This is an issue because many library like Axios automatically transform the objects like the Date object. Another problem is that in order to convert the date it's required to implement some extra logic in the parent component that can transform the date.

I propose two solutions to this problem:

1. Allow to return the model as string. For example in my primevue fork I added a new property with the name "outputFormat" and then I modified the updateModel method in order of optionally return the model as string:

 ```
updateModel(value) {

        if (this.outputFormat && value) {
            if (Array.isArray(value))
                value = value.map(date => date ? this.formatDate(date, this.outputFormat) : date);
            else
                value = this.formatDate(value, this.outputFormat)
        }

        this.$emit('input', value);
    }
```

```
updateModelTime() {
...
        value = value ? new Date(value).getTime() : new Date();
...
}
```

This solution has many advantages because what the user selects is exactly what it can be send to the back-end and the back-end can save the dates without taking care of timezone transformation and the parent component can represent the value directly. Another advantage is that we can control the date format returned using the formatDate function that you already created.

2. Allow to optionally force to use "UTC" to the calendar component, so there is not transformation on the model when is returned to the parent.


For more info about JS serialization issue see:
https://stackoverflow.com/questions/1486476/json-stringify-changes-time-of-date-because-of-utc

**Comment by tudorels** [comment]
I've made a fork of your primevue-quickstart and I put the example https://github.com/tudorels/primevue-quickstart
Thanks!

**Comment by cagataycivici** [comment]
We tried both in the past for PrimeNG and it caused maintenance issues for us in addition to huge complexity to an already complex component so we left it to the page author and do not intervene the conversion or communication with the server.

**Comment by craiggeil** [comment]
Wow this is a complete failure with this component if this is left as is. Who does this??

**Comment by anchan42** [comment]
I think it is probably for the best. For a site that does not need to work across time zones, taking the time zone out completely might be the simplest answer: 
With luxon, run this with model data before sending it to server:

```
//Make jsDateTime timezone agnostic
const removeTz = (jsDate) => {
  return DateTime.fromJSDate(jsDate).toISO({ includeOffset: false });
};
```

If the site needs to deal with time zones, we would need a systematic set-up for the whole site logic.  The problem would not be resolved with one component. Trying to fix this on the component level might actually get in the way becuase the problem is not on the way that data get into the backend but on the way out and displayed to user.
