### ISSUE TITLE
Select: Cannot read properties of null (reading '$el') - filter and auto-filter-focus error

### ISSUE THREAD

**Issue by Tamas-hi** [primefaces/primevue#6793]
### Describe the bug

Following up on #6539 , this problem is still occurs when you click out of the open dropdown.
Previous fix was not sufficient.

### Reproducer

https://stackblitz.com/edit/lhc6ls?file=src%2FApp.vue

### PrimeVue version

4.2.2

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Brave

### Steps to reproduce the behavior

1. Open the reproducer link.
2. Open console
3. Click on the dropdown and then click out of it.
4. See the error

### Expected behavior

No error message

**Comment by sivareddyuppathi** [comment]
Fix for the above issue.

PR: https://github.com/primefaces/primevue/pull/6787

**Comment by SamGeodynamics** [comment]
updated everything to 4.2.3 but it's still giving the same error

**Comment by parkersprouse** [comment]
Hi @tugcekucukoglu, I just want to make sure the state of this issue receives the necessary attention to help clear up any confusion and prevent it from slipping through the cracks.

Like @SamGeodynamics mentioned, this issue was marked as `completed`, but the initial PR ([#6787](https://github.com/primefaces/primevue/pull/6787)) that attempted to fix it was closed without being merged in due to attempting to resolve multiple issues in a single PR.

So then the author of the original PR split out the work for the `Select` fix into a new PR ([#6839](https://github.com/primefaces/primevue/pull/6839)) as requested, but the PR was closed under the false assumption that the fix for the `Select` issue had already been merged in when it hadn't.

And now when new issues ([#6804](https://github.com/primefaces/primevue/issues/6804)) get opened mentioning the same problem, they get closed as duplicates.

I'm sure this is nothing more than a misunderstanding and/or an oversight from jumping between the various issues and PRs, but as for where things currently stand, a fix for the `Select` filtering focus issue has not been merged in or made available in any released version of the library, requiring local patching for it to be included.

**Comment by ellisj98** [comment]
This is also an issue that is affecting my production code.

**Comment by Tamas-hi** [comment]
Should we open another issue? I think this is still a problem.

**Comment by nexgen-ui** [comment]
Yes, it is still an issue. I logged the [#6804](https://github.com/primefaces/primevue/issues/6804) issue and am still waiting for a fix. This bug should have a higher priority in my view as it happens on every single dropdown list with auto focus filter property enabled. I had to roll my code back to version 4.0.7 because of this bug.

**Comment by ronaldtveen** [comment]
Same, running @primevue/core v4.2.5 and am getting the same error in production.

**Comment by ronaldtveen** [comment]
Same, running @primevue/core v4.2.5 and am getting the same error in production. 

@tugcekucukoglu Could you please reply to @parkersprouse 's questions? 
Is this still being worked on since this is a closed issue? It is not yet resolved...

**Comment by PrzemekTk** [comment]
the solution is simple
if you have filter true you might set autoFilterFocus to true
if filter is false, you have to always set autoFilterFocus to fale.
