### ISSUE TITLE
AutoComplete: Design tokens are not being used

### ISSUE THREAD

**Issue by fatihsolhan** [primefaces/primevue#6828]
### Describe the bug

AutoComplete component is not using the [listed design tokens in the documentation](https://primevue.org/autocomplete/#theming.tokens)
![image](https://github.com/user-attachments/assets/2123ba8c-b76b-4ceb-b685-889bb000f886)

It uses `inputtext` tokens instead.

![image](https://github.com/user-attachments/assets/40296339-e782-4f89-9f2d-e9055d981801)

Here is the discussion link as well: https://github.com/orgs/primefaces/discussions/3067

### Reproducer

https://stackblitz.com/edit/atybs1-swvfn3?file=src%2FApp.vue

### PrimeVue version

4.2.2

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Nuxt

**Comment by fatihsolhan** [comment]
Update:

I noticed it's being used when it's in multiple mode:
![image](https://github.com/user-attachments/assets/feb39c04-3509-4f79-828c-56632a43fd6b)
  https://github.com/primefaces/primevue/blob/312bf677ea06d92e84e9e4cb1c4001c755c6dd63/packages/primevue/src/autocomplete/AutoComplete.vue#L1-L4

**Comment by j0rgedev** [comment]
You're absolutely right, @fatihsolhan. The issue appears when the multiple prop is enabled because the InputText becomes visible, and it brings its own design tokens.

Here's what I've attempted so far to solve this:
1. Imitating the ToggleButton
I tried to follow the approach used by the ToggleButton component because I thought it'd use the Button component; however, it does not since itonly applies its styles. However, this wouldn't work for the Autocomplete component because it requires the full functionality of InputText, so let's discard this attempt.

2. Adding Styles to p-autocomplete-input
I noticed that the p-autocomplete-input class is being applied to the InputText, but not its styles, so i added them in the [AutoCompleteStyle.js](https://github.com/primefaces/primevue/blob/master/packages/primevue/src/autocomplete/AutoComplete.vue) file. Unfortunately, these styles are being overridden by the default InputText styles.

![image](https://github.com/user-attachments/assets/357494de-d65a-4a8a-8938-d42e12ef7d2d)

3. Disabling styled Prop for InputText
I found that if I set the styled prop of InputText to false and create new design tokens for `p-autocomplete-input`, it starts working. This approach prevents the override issue. I just created the `autocomplete.inputtext.background` dt  which should be applied like this:
```js
myAutoComplete: {
    border: {
        color: 'blue',
    },
    inputtext: {
        background: 'red',
    },
}
```
new AutoComplete.js file:
```js
const theme = ({ dt }) => `
.p-autocomplete-input {
    font-family: inherit;
    font-feature-settings: inherit;
    font-size: 1rem;
    color: ${dt('inputtext.color')};
    background: ${dt('autocomplete.inputtext.background')}; //new dt
    padding-block: ${dt('inputtext.padding.y')};
    padding-inline: ${dt('inputtext.padding.x')};
    border: 1px solid ${dt('inputtext.border.color')};
    transition: background ${dt('inputtext.transition.duration')},
                color ${dt('inputtext.transition.duration')},
                border-color ${dt('inputtext.transition.duration')},
                outline-color ${dt('inputtext.transition.duration')},
                box-shadow ${dt('inputtext.transition.duration')};
    appearance: none;
    border-radius: ${dt('inputtext.border.radius')};
    outline-color: transparent;
    box-shadow: ${dt('inputtext.shadow')};
}
// more styles ....
`;
```
However, there is a downside for this approach. As you saw in the code above, I'm reusing the InputText design tokens for the rest of the styles (e.g color, padding, etc), so to solve that, we'll just need to create new design tokens like I did for the background, which makes sense, right? 

Conclusion
The third option seems like the most logical solution to me. I can open a PR to show the results, but it know might get rejected as there could be better solutions.

Let me know your thoughts!

**Comment by tugcekucukoglu** [comment]
Thanks for the solution. We think topic can be moved to discussions.

**Comment by fatihsolhan** [comment]
@tugcekucukoglu Actually, @j0rgedev has already identified the root cause and proposed some solid solutions here. This seems like a legitimate bug where the AutoComplete component isn't properly using its own design tokens when not in multiple mode. Since it's a component behavior issue, wouldn't it make more sense to keep it as an issue?

**Comment by j0rgedev** [comment]
@tugcekucukoglu I was waiting for any feedback before opening a PR, but I guess I'll just open it and wait for any feedback there before getting merged

**Comment by fatihsolhan** [comment]
@j0rgedev I was really busy these last days and couldn't properly respond to your proposal - I apologize for keeping you waiting.
I also liked your third solution, please go ahead with the PR
