### ISSUE TITLE
Layout Components

### ISSUE THREAD

**Issue by go4cas** [primefaces/primevue#683]
Some UI libs have layout components (Layout, Header, Footer, Content, etc) to make layout design more convenient.

Example: [Quasar](https://quasar.dev/layout/layout).

**Comment by dheimoz** [comment]
Hello @go4cas, I strongly believe that PrimeFlex sorts much of use cases. So far PrimeVue is much performant than other UI Libs. With their minimalistic approach you can even score more than 80 in LightHouse in mobile devices. As stated, just my opinion.

**Comment by some-user123** [comment]
I'd really appreciate such components incl. sidebar. Many other frameworks have them as well ([Vuetify](https://vuetifyjs.com/en/components/navigation-drawers/), [CoreUI](https://coreui.io/vue/docs/components/sidebar.html), [Buefy](https://buefy.org/documentation/sidebar), ...).

Of course, it can be done using lots of SCSS (like in [sigma-vue](https://github.com/primefaces/sigma-vue/tree/master/src/assets/layout)). But I'd rather not copy this code. I don't understand it, I don't want to maintain it, I'd prefer a component that encapsulates it.

I really like primevue, but for me that's a blocker at the moment to use a different framework, which allows me to much faster create and start with a useable UI.

**Comment by dheimoz** [comment]
Hello @some-user123 
SASS it’s a superset of CSS, which means essentially all valid CSS is valid SCSS as well (not my words but  https://sass-lang.com/documentation/syntax) . Sorry in advance if my next comment sounds a little bit harsh. I do not believe it is an a valid argument saying that just because you do not understand the syntax, Prime Vue should create the Layout Components. 

@go4cas had given several suggestions that made sense to @cagataycivici. Because of those, the next milestone seems mind blowing. I must thanks both of them, because their efforts are making PrimeVue greater.

@go4cas solid arguments convinced the right people.

Also, with PrimeFlex you might not need SASS, you only need to understand Flexbox. The concept has been around for ages https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Basic_Concepts_of_Flexbox

Sarah Ming has an excellent series to easily digest the concept: https://www.samanthaming.com/flexbox30/

It is worthwhile to give it a try. 

Fortunately for us, people at PrimeFaces have the last call and might decide to incorporate the suggested components.

With all being said, if you do need the Layout Components right now, perhaps PrimeVue PRO support is what you require. 

As previously stated, it is just my personal opinion. I do not mean to offend anyone.

**Comment by some-user123** [comment]
Thanks for your elaborate comment @dheimoz.

Maybe I should have been more detailed in my thoughts. You are right, there is a Sidebar component in PrimeVue. However, it only works as an overlay. You can't compare it, e.g. with what vuetify provides. The vuetify navigation drawer can  be used as an overlay on small screens, but also as a permanent layout part on larger screens. It has a minified version that automatically expands, etc. The list elements inside the drawer immediately have the right design.

Of course, I could do all the same by myself. But isn't that the reason we use libraries? To not do everything from scratch... to re-use functionality...

In vuetify (as an example) I can have a drawer, a header, etc. with one html element each. It slides in and out, and I don't have to take care of it and looks sufficiently nice. If I want to improve the styling, I can change that later on. I can change functionality (use minified version and expand on hover) within the limitations of the framework. I can also completely replace it with some custom component, if I want something special. But I don't have to.

I also don't want to offend you or anybody at PrimeFaces. I'm just telling, that to me (and I'm just some user ;-)) it would be a big benefit if PrimeVue would allow to compose my layout consisting of header, footer, sidebar just by using layout components (like other libraries do).

Nobody should be forced to use them. Just as an option. Maybe that's of use for other people as well, maybe it isn't.

Please don't forget, why I'm writing here. Because I really like PrimeVue, its components, its look & feel. However, points like the above make it easier (for me) to use Vuetify for any new project than using PrimeVue.

**Comment by dheimoz** [comment]
Hey @some-user123 I love debating ideas and I am glad you did not take nothing personal.

What you are describing is precisely why it is taking them much more time to upgrade to Vue 3. Extremely tight coupled components make them harder to maintain. I really love Vuetify, it is my main preference for long term stability, but its initial size make it harder to justify, at least for the projects I work on, that depend on light bundles like PWA's.

With all being said, I really support the approach that PrimeVue is taking. It provides with the much more complex requirements and let you style as needed. On top of that, they provide a Theme Designer  https://www.primefaces.org/designer-vue/#/

As mentioned, @cagataycivici will make the last decision.

**Comment by cagataycivici** [comment]
Thanks for the feedback, our premium dashboards are created for this functionality but we'll still discuss this internally at our team.

**Comment by cagataycivici** [comment]
This requirement will be covered by the upcoming PrimeBlocks for PrimeVue project and also already kind of available in existing templates as pre designed layouts.
