### ISSUE TITLE
headerClass for Column is not applied

### ISSUE THREAD

**Issue by tudorels** [primefaces/primevue#861]
Hello, I'm trying to set headerClass for Datatable Column and is not applying, if I use headerStyle is working correctly. There is an example somewhere on your sites on how to use the headerClass on Column?  Now I'm using **3.0.2** version, but I tried with **3.1.2** and no change.

**Comment by cagataycivici** [comment]
I'm unable to replicate, see the images please.
<img width="863" alt="Screen Shot 2021-01-20 at 11 53 45" src="https://user-images.githubusercontent.com/686247/105150870-55b0f280-5b16-11eb-951c-bfa00f8ec5d0.png">
<img width="403" alt="Screen Shot 2021-01-20 at 11 54 31" src="https://user-images.githubusercontent.com/686247/105150885-59447980-5b16-11eb-8097-1235d7ffc414.png">

**Comment by WhyKickAmooCow** [comment]
I have run into this trying to use headerClass for horizontal scrolling. 

When using headerStyle, the style is applied to the header and colgroups in the body and footer. This isn't the case when using headerClass. The expected behavior was to apply the class to the header and colgroups like with headerStyle, but instead it is only applied to the table header. This results in the header being larger than the body and stops the horizontal scrolling from working as expected.

**Comment by WhyKickAmooCow** [comment]
I have made a [fork](https://github.com/WhyKickAmooCow/primevue
) that should work if you are indeed facing the same issue I am.

**Comment by bzapata-thr** [comment]
> I'm unable to replicate, see the images please.
> <img alt="Screen Shot 2021-01-20 at 11 53 45" width="863" src="https://user-images.githubusercontent.com/686247/105150870-55b0f280-5b16-11eb-951c-bfa00f8ec5d0.png">
> <img alt="Screen Shot 2021-01-20 at 11 54 31" width="403" src="https://user-images.githubusercontent.com/686247/105150885-59447980-5b16-11eb-8097-1235d7ffc414.png">

is this for v3? Because it does not work in v2

**Comment by waqas-ali-pk** [comment]
@cagataycivici @bzapata-thr 
FYI: Class will be applied as mentioned by @cagataycivici , but this will not impact the style of header.
I try to apply custom style using using class (e.g. changed background and text color), class was appearing on the header (when I inspect it in browser), but the style was not applying.

Any idea,  why is this?
