### ISSUE TITLE
Custom target for OverlayPanel

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primevue#942]
Similar to PrimeFaces, add a target option to Overlay to display the panel relative to a specific element, should use the event target by default.

**Comment by steineggerroland** [comment]
We tackle several problems with OverlayPanels, because they don't behave like documented.

Our selenium frontend tests don't work properly, because the implementation uses the currentTarget of the event, which "is only available while the event is being handled", as stated in the [specification](https://developer.mozilla.org/en-US/docs/Web/API/Event/currentTarget). When handling events asynchronously this might lead to a null `target` and exceptions when showing and aligning the OverlayPanel.

This could fix the issue. In my opinion, event.target and not event.currentTarget should be used to align the Panel.
