### ISSUE TITLE
PrimeVue DataTable bug

### ISSUE THREAD

**Issue by hradev** [primefaces/primevue#977]
hi There,

I think I found a bug on the PrimeVue demo,

when you go to Datatable -> Documentation -> first table on page, search by name, remove search, pagination doesn't work anymore.

I picked up the problem in my project, and checked the demo does the same .

Regards,
H

**Comment by luke-z** [comment]
I've seen that the issue has been fixed in version 3.x.
But the problem still exists with the latest 2.x version, 2.4.2. 

As we are developing with nuxtjs at the moment, we cannot update to primevue 3 yet.

I noticed that it happens as soon as the filters object has a key inside.
As long as an empty object is passed to the filters prop on DataTable, the pagination works.

But the moment it receives a key through v-model changes for example, the pagination stops working.

I tried

```
filters: {
   global: null
}

filters: {
   global: ""
}

But only an empty object works:
filter: {}
```

A workaround would be to remove the key as soon as the value is empty. But filtering often leaves us with more than one page of results, which are be inaccessible at the moment.
