### ISSUE TITLE
DataTable, Advanced Cell Editing, "reverting values with the escape key" does not work

### ISSUE THREAD

**Issue by cybay** [primefaces/primevue#989]
https://www.primefaces.org/primevue/showcase/#/datatable/edit

What I do:
1. click with mouse at any value in table. It leads to editing mode.
2. edit value, change it somehow
3. press keyboard button 'Escape'

What I expect:
-- exit from edit mode, value reverted, editing/changes canceled

What I have/see:
-- exit from edit mode,  == all changes applied ==

Is it correct behaviour???

As well I can't see that handler for event @cell-edit-cancel is called.

**Comment by blurbiness** [comment]
That is an expected behaviour in "basic cell editing", because when binding the editor input component directly with v-model, the model will be updated directly.

As they said in documentation and as they demonstrate in "advanced cell editing" demo, you should use `:modelValue` and ` @update:modelValue` to have full control on editing. Then, you would be able to keep a editing version of the model and decide what to do finally in `@cell-edit-complete`event. For example, to validate the value and cancel with `preventDefault`if not valid, or commit in a Vuex store, etc.

**Comment by cagataycivici** [comment]
The response is correct.
